### ISSUE TITLE
Bug:   panic: XTLS Splice: not TCP inbound

### ISSUE THREAD

**Issue by vinograd-cyber** [XTLS/Xray-core#1342]
xtls-rprx-vision

Xray 1.6.4 (Xray, Penetrates Everything.) Custom (go1.19.3 linux/amd64)
A unified platform for anti-censorship.
2022/11/15 16:00:19 [Info] infra/conf/serial: Reading config: /opt/PROXJECT-ec3b/app/xray/etc/c.json

以下是造成xray不断进程崩溃停止的bug：
**_panic: XTLS Splice: not TCP inbound_**

goroutine 65 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead.func1({0x11e6818, 0xc000473780}, {0x11ed558?, 0xc000306028}, {0x0, 0x0}, {0x11e5aa0?, 0xc0003064c0}, 0xc03a78fde0, 0xc04e2f1122, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:283 +0xa98
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead({0x11d9ac0, 0xc000160940}, {0x11db160?, 0xc035974090?}, {0x11d9ec0?, 0xc00bf3c7b0?}, {0x11ed558?, 0xc000306028?}, {0x11e5aa0, 0xc0003064c0}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:323 +0x10f
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:280 +0x574
github.com/xtls/xray-core/common/task.OnSuccess.func1()
        github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0x0?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde

==================================================================================
`  "outbounds": [
    {
      "tag": "nemghcaa-proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "c3926708.fjadjakfdfjadkf.asia",
            "port": 47772,
            "users": [
              {
                "id": "9d9c0153-ab41-4f93-b6b1-a6e6cb7a722d",
                "encryption": "none",
                "flow": "xtls-rprx-vision",
                "level": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "c3926708.fjadjakfdfjadkf.asia",
          "allowInsecure": false,
          "fingerprint": "randomized"
        }
      }
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "nemghcaa-direct"
    },`

**Comment by yuhan6665** [comment]
very strange, I can't reproduce this issue. Can you post your full config? What is your device? What client software did you used?

**Comment by hkbase** [comment]
我遇到的情况跟楼主是一样的。
xray version 1.6.4
xray的配置信息：
入站：vmess+tcp+http伪装
出站：xtls-rprx-vision+tcp+tls+chrome

遇到的问题：
一打开youtube站点，xray客户端就会崩溃

下面附上客户端xray的崩溃日志：
Xray 1.6.4 (Xray, Penetrates Everything.) Custom (go1.19.3 linux/amd64)
A unified platform for anti-censorship.
2022/11/16 09:20:10 Using config from env:  /usr/local/etc/xray/config.json
2022/11/16 09:20:10 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
2022/11/16 09:20:10 [Debug] app/log: Logger started
2022/11/16 09:20:10 [Info] app/dns: DNS: created UDP client initialized for 127.0.0.1:53
2022/11/16 09:20:11 [Debug] app/router: MphDomainMatcher is enabled for 59080 domain rule(s)
2022/11/16 09:20:11 [Debug] app/router: MphDomainMatcher is enabled for 162 domain rule(s)
2022/11/16 09:20:11 [Debug] app/router: MphDomainMatcher is enabled for 66609 domain rule(s)
2022/11/16 09:20:11 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:8006
2022/11/16 09:20:11 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:80
2022/11/16 09:20:11 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:1080
2022/11/16 09:20:11 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:8080
2022/11/16 09:20:11 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:8006
2022/11/16 09:20:11 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:80
2022/11/16 09:20:11 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1080
2022/11/16 09:20:11 [Info] transport/internet/udp: listening UDP on 0.0.0.0:1080
2022/11/16 09:20:11 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:8080
2022/11/16 09:20:11 [Warning] core: Xray 1.6.4 started
2022/11/16 09:20:34 123.139.60.28:42222 accepted tcp:s.youtube.com:443 [tcp8006-in >> oracle]
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/outbound: tunneling request to tcp:s.youtube.com:443 via 129.154.215.21:443
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsFilterTls13 found tls client hello! 763
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsPadding 763 568 0
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: Xtls Unpadding new block0 16 content 374 padding 990 0
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsFilterTls13 found tls 1.3! 374 TLS_AES_128_GCM_SHA256
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsPadding 74 963 0
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsPadding 98 924 2
2022/11/16 09:20:34 [Info] [2435714803] proxy/vless/encoding: XtlsWrite writeV 1 2069 0
panic: XTLS Splice: not TCP inbound

goroutine 122 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead.func1({0x11e6818, 0xc000ad2a40}, {0x11ed558?, 0xc00011f358}, {0x0, 0x0}, {0x11e5aa0?, 0xc000013098}, 0xc000b02de0, 0xc000ab9cce, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:283 +0xa98
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead({0x11d9ac0, 0xc000a659e0}, {0x11db160?, 0xc00011f348?}, {0x11d9ec0?, 0xc000afd9e0?}, {0x11ed558?, 0xc00011f358?}, {0x11e5aa0, 0xc000013098}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:323 +0x10f
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:280 +0x574
github.com/xtls/xray-core/common/task.OnSuccess.func1()
        github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0xc000a86c00?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde

**Comment by vinograd-cyber** [comment]
> very strange, I can't reproduce this issue. Can you post your full config? What is your device? What client software did you used?

感谢您的重视，我使用的是最新的版本1.6.4 linux-amd64， 配置检测OK，启动也正常，当流量路由给海外的时候，xray进程就自动报错panic后退出了进程，前提是我开启了新特性："flow": "xtls-rprx-vision"。 如果换为传统的其他方式，1.6.4没异常。我想碰到同样问题的不止我一个人。我也试图去掉kcptun中间层，用c直连s，也会发生 panic。
我使用的操作系统：
```
   operating system: debian gnu/linux 11 (bullseye)
      system version: 11.5                
       system kernel: 5.10.0-19-amd64     
        product name: b85m-d2v-si         
       serial number: to be filled by o.e.m.
     processor model: intel(r) core(tm) i3-4170 cpu @ 3.70ghz
   processor threads: 4                   
     processor cores: 1                   
  processor bogomips: 7383.32             
     physical memory: DDR3 1600MT/s 8(gb)               
        main adapter: enp2s0: 192.168.23.6
```
架构是：Qv2ray2.7.0 ——>>xray client(CN) —>kcptun client (CN)——>kcptun server（US CA）——>xray server(US CA)
客户端配置：
```
{
    "log": {
        "loglevel": "warning",
        "access": "$b8c159359c6d/app/xray/logs/access.log",
        "error": "$b8c159359c6d/app/xray/logs/error.log",
        "dnsLog": false
    },
  "dns": {
    "servers": [
      {
        "address": "https+local://adfree.fjadfjafja.com/dns-query",
        "domains": [
          "geosite:cn",
          "ext:h1y.dat:cn",
          "domain:fjadfjafja.com"
        ],
        "expectIPs": [
          "ext:geoip-only-cn-private.dat:cn"
        ],
        "skipFallback": false
      },
      {
        "address": "https+local://adfree.fjadfjafja.com/dns-query",
        "domains": [
          "geosite:geolocation-!cn",
          "ext:h1y.dat:gfw"
        ],
        "skipFallback": false
      },
      {
        "address": "https+local://adfree.fjadfjafja.com/dns-query"
      },
      "119.29.29.29",
      "114.114.114.114",
      "114.114.115.115",
      "223.5.5.5",
      "223.6.6.6",
      "101.226.4.6",
      "218.30.118.6",
      "123.125.81.6",
      "140.207.198.6",
      "180.76.76.76",
      "1.0.0.1",
      "64.6.64.6",
      "localhost"
    ],
    "clientIp": "${wanip:-114.221.193.85}",
    "queryStrategy": "UseIP",
    "disableCache": false,
    "disableFallback": false,
    "disableFallbackIfMatch": true,
    "tag": "feiitoeipg"
  },
    "inbounds": [
        {
            "port": 4001,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "0fda3f51-3b66-4283-b360-d8e9e0680f03"
                    }
                ]
            }
        },
        {
            "port": 4002,
            "protocol": "vless",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "fakedns",
                    "quic"
                ],
                "metadataOnly": false,
                "routeOnly": true
            },
            "settings": {
                "clients": [
                    {
                        "id": "5378a98a-f5cf-4ac5-a504-94e7f43dc217",
                        "level": 0,
                        "flow": "xtls-rprx-direct",
                        "email": "xugang@microsoft.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "learn.microsoft.com:80",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "learn.microsoft.com:80",
                        "xver": 1
                    }
                ],
                "network": "tcp,udp",
                "followRedirect": true
            },
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": true
                },
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "maxVersion": "1.3",
                    "allowInsecure": true,
                    "disableSystemRoot": true,
                    "fingerprint": "randomized",
                    "rejectUnknownSni": true,
                    "certificates": [
                        {
                            "certificateFile": "${b8c159359c6d}/ssl/crtwv.pem",
                            "keyFile": "${b8c159359c6d}/ssl/crtwv.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            },
            "tag": "ndeiewerdnet"
        },
        {
            "listen": "127.0.0.1",
            "port": 4003,
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "fakedns",
                    "quic"
                ],
                "metadataOnly": false,
                "routeOnly": true
            },
            "settings": {
                "auth": "password",
                "accounts": [
                    {
                        "user": "etenvr",
                        "pass": "6LVSXELMR6eCoU55TwPa7imTPoA="
                    }
                ],
                "udp": true,
                "network": "tcp,udp",
                "followRedirect": true
            },
            "tag": "eolhh"
        }
    ],
    "outbounds": [
        {
            "tag": "nemghcaa-proxy",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "${faa56868711d}",
                        "port": ${db08c5cd8f97},
                        "users": [
                            {
                                "id": "${f287f434c0c8}",
                                "encryption": "none",
                                "flow": "xtls-rprx-vision",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "${faa56868711d}",
                    "allowInsecure": false,
                    "fingerprint": "randomized"
                }
            }
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "tag": "nemghcaa-direct"
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "nemghcaa-block"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "domainMatcher": "hybrid",
            "rules": [
                {
                    "type": "field",
                    "outboundTag": "nemghcaa-direct",
                    "protocol": [
                        "bittorrent"
                    ]
                },
                {
                    "domain": [
                        "domain:fjadfjafja.com"
                    ],
                    "type": "field",
                    "outboundTag": "nemghcaa-direct"
                },
                {
                    "domain": [
                        "ext:h1y.dat:rej",
                        "geosite:category-ads-all"
                    ],
                    "type": "field",
                    "outboundTag": "nemghcaa-block"
                },
                {
                    "ip": [
                        "geoip:rej",
                        "ext:geoip-only-cn-private.dat:private"
                    ],
                    "type": "field",
                    "outboundTag": "nemghcaa-block"
                },
                {
                    "type": "field",
                    "outboundTag": "nemghcaa-proxy",
                    "domain": [
                        "geosite:geolocation-!cn",
                        "ext:h1y.dat:gfw",
                        "domain:dns10.quad9.net",
                        "domain:cloudflare-dns.com"
                    ]
                },
                {
                    "type": "field",
                    "outboundTag": "nemghcaa-proxy",
                    "ip": [
                        "64.6.64.6",
                        "64.6.65.6"
                    ]
                },
                {
                    "type": "field",
                    "outboundTag": "nemghcaa-direct",
                    "domain": [
                        "geosite:cn",
                        "ext:h1y.dat:cn"
                    ]
                },
                {
                    "type": "field",
                    "outboundTag": "nemghcaa-direct",
                    "ip": [
                        "127.0.0.1/32",
                        "119.29.29.29",
                        "114.114.114.114",
                        "114.114.115.115",
                        "223.5.5.5",
                        "223.6.6.6",
                        "101.226.4.6",
                        "218.30.118.6",
                        "123.125.81.6",
                        "140.207.198.6",
                        "180.76.76.76",
                        "ext:geoip-only-cn-private.dat:cn"
                    ]
                }
            ]
        }
    },
    "policy": {
        "levels": {
            "0": {
                "handshake": 4,
                "connIdle": 300,
                "uplinkOnly": 0,
                "downlinkOnly": 0,
                "statsUserUplink": false,
                "statsUserDownlink": false,
                "bufferSize": 4096,
                "connection": -1
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false,
            "statsOutboundUplink": false,
            "statsOutboundDownlink": false
        }
    }
}
```
服务端配置是：
```
{
    "log": {
        "access": "$b8c159359c6d/app/xray/logs/access.log",
        "error": "$b8c159359c6d/app/xray/logs/error.log",
        "loglevel": "warning",
        "dnsLog": false
    },
    "dns": {
        "servers": [
            "1.0.0.1",
            "64.6.64.6",
            "64.6.65.6",
            "8.8.8.8"
        ],
        "clientIp": "$wanip",
        "queryStrategy": "UseIP",
        "disableCache": false,
        "disableFallback": false,
        "disableFallbackIfMatch": true,
        "tag": "dmoshwtteuystu"
    },
    "inbounds": [
        {
            "tag": "uoarrlclntd",
            "listen": "127.0.0.1",
            "port": ${e067922e9be0},
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${f287f434c0c8}",
                        "flow": "xtls-rprx-vision",
                        "level": 0,
                        "email": "gaegaocoo@live.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "www.update.microsoft.com:80"
                    },
                    {
                        "alpn": "h2",
                        "dest": "update.microsoft.com:80",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                  "rejectUnknownSni": true,
                  "certificates": [
                    {
                        "certificateFile": "${b8c159359c6d}/ssl/etces.pem",
                        "keyFile": "${b8c159359c6d}/ssl/etces.key"
                    }
                  ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            }
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "block"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": []
        }
    },
    "policy": {
        "levels": {
            "0": {
                "handshake": 4,
                "connIdle": 300,
                "uplinkOnly": 0,
                "downlinkOnly": 0,
                "statsUserUplink": false,
                "statsUserDownlink": false,
                "bufferSize": 2048,
                "connection": -1
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false,
            "statsOutboundUplink": false,
            "statsOutboundDownlink": false
        }
    }
}
```

**Comment by yuhan6665** [comment]
我知道了你们的中转配置里面 inbound 是 vmess，所以无法使用 Vision。因为 Vision 本质上还是 XTLS，使用在出站的时候要求入站是[任意门、Socks、HTTP 等纯净的 TCP 连接](https://github.com/XTLS/Xray-core/releases/tag/v1.1.2)
你们可以把中转的入站也改成 VLESS (+TLS) 应该就可以了，如果是内网，改成socks也可以

**Comment by hkbase** [comment]
同样的这套配置，使用xray 1.6.1版本，中转机改为xtls-rprx-splice+tcp+xtls，国外vps改为xtls-rprx-direct+tcp+xtls，在手机v2rayNG上使用vmess+tcp+http伪装，是可以正常使用的。

**Comment by yuhan6665** [comment]
有点奇怪 我有空测一下

**Comment by vinograd-cyber** [comment]
> 我知道了你们的中转配置里面 inbound 是 vmess，所以无法使用 Vision。因为 Vision 本质上还是 XTLS，使用在出站的时候要求入站是[任意门、Socks、HTTP 等纯净的 TCP 连接](https://github.com/XTLS/Xray-core/releases/tag/v1.1.2) 你们可以把中转的入站也改成 VLESS (+TLS) 应该就可以了，如果是内网，改成socks也可以
十分感谢您的指导，我明白了。但有个疑惑还望解答，就是我虽然配置了入栈代理三个方式socks，vmess和vless，我实际上在工作站电脑上安装的客户端（之前是qv2ray,昨天换成了v2rayN）与中转侧接入时候用的是vless+xtls协议，也就说我并未用到socks和vmess，那么是不是我需要把客户端软件的xtls改成tls，或者从中转侧配置中去掉inbound里面的vmess？以下是我的v2rayN客户端的配置：
```
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      **"protocol": "vless",**
      "settings": {
        "vnext": [
          {
            "address": "accelerator.fjadfjafja.com",
            "port": 4002,
            "users": [
              {
                "id": "d0326c4f-c8d2-41bc-ac78-b286622c121e",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                **"flow": "xtls-rprx-direct"**
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        **"security": "xtls",**
        "xtlsSettings": {
          "allowInsecure": true,
          "serverName": "vpngo.fjadfjafja.com",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "fingerprint": "randomized"
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
```

**Comment by hkbase** [comment]
> 有点奇怪 我有空测一下
在使用xray 1.6.1版本下，小结一下：
1、在中转机上配置xtls-rprx-direct这个协议，使用vmess入站数据可以被正常路由到国外vps。
2、在中转机上配置xtls-rprx-splice这个协议，xray进程会崩溃。
崩溃的日志如下：
```
2022/11/16 14:10:24 [Debug] transport/internet: dialing to tcp:193.123.244.21:8443
2022/11/16 14:10:24 [Info] [2923283659] proxy/vless/outbound: tunneling request to tcp:rr7---sn-ab02a0nfpgxapox-jwwy.googlevideo.com:443 via X.X.X.X:8443
2022/11/16 14:10:24 [Info] [1166697687] proxy/vless/outbound: tunneling request to tcp:rr7---sn-ab02a0nfpgxapox-jwwy.googlevideo.com:443 via X.X.X.X:8443
panic: XTLS Splice: not TCP inbound

goroutine 71 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0xc00011ed20, {0x11d7280, 0xc0001b9a10}, {0x0, 0x0}, {0x11d6470?, 0xc00011ed38}, 0xc0009d9e18, {0x11ca8e0, 0xc0002e9890}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:209 +0x675
github.com/xtls/xray-core/proxy/vless/encoding.ReadV({0x11ca4e0, 0xc0009b4810}, {0x11cbb80?, 0xc000012988?}, {0x11ca8e0?, 0xc0002e9890?}, 0xc0002e85a0?, {0x11d6470?, 0xc00011ed38?}, {0x0, ...}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:235 +0xa5
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:239 +0x465
github.com/xtls/xray-core/common/task.OnSuccess.func1()
        github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0x0?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde
```

**Comment by hkbase** [comment]
> 有点奇怪 我有空测一下

在使用xray 1.6.1版本下，小结一下：
1、在中转机上配置xtls-rprx-direct这个协议，使用vmess入站数据可以被正常路由到国外vps。
2、在中转机上配置xtls-rprx-splice这个协议，xray进程会崩溃。
崩溃的日志如下：
```
2022/11/16 14:10:24 [Debug] transport/internet: dialing to tcp:193.123.244.21:8443
2022/11/16 14:10:24 [Info] [2923283659] proxy/vless/outbound: tunneling request to tcp:rr7---sn-ab02a0nfpgxapox-jwwy.googlevideo.com:443 via X.X.X.X:8443
2022/11/16 14:10:24 [Info] [1166697687] proxy/vless/outbound: tunneling request to tcp:rr7---sn-ab02a0nfpgxapox-jwwy.googlevideo.com:443 via X.X.X.X:8443
panic: XTLS Splice: not TCP inbound

goroutine 71 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0xc00011ed20, {0x11d7280, 0xc0001b9a10}, {0x0, 0x0}, {0x11d6470?, 0xc00011ed38}, 0xc0009d9e18, {0x11ca8e0, 0xc0002e9890}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:209 +0x675
github.com/xtls/xray-core/proxy/vless/encoding.ReadV({0x11ca4e0, 0xc0009b4810}, {0x11cbb80?, 0xc000012988?}, {0x11ca8e0?, 0xc0002e9890?}, 0xc0002e85a0?, {0x11d6470?, 0xc00011ed38?}, {0x0, ...}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:235 +0xa5
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:239 +0x465
github.com/xtls/xray-core/common/task.OnSuccess.func1()
        github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0x0?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde
```

**Comment by chika0801** [comment]
如果你中转机在墙外，出站开ss tcp 吧，何必研究这么多了。

**Comment by hkbase** [comment]
> 如果你中转机在墙外，出站开ss tcp 吧，何必研究这么多了。

我的中转机在国内，负责把入站流量智能分流，实现国内流量直接转发，国外流量路由到国外vps。

**Comment by chika0801** [comment]
要不你去墙外买台vps 当中转机。

不的话，你出站用hy协议到墙外机了？

**Comment by hkbase** [comment]
我的猜想：
这个程序崩溃，是由于新的vision协议，默认就是支持splice，引入的这个崩溃。
而老协议根据使用场景，是区分direct和splice的，官方文档也说了，splice并不适用于所有场景。
而我当前使用的是vmess入站，只能适用于direct这个协议。

**Comment by yuhan6665** [comment]
@hkbase 你的结果是对的 感谢测试 下个版本会改进 vision 的逻辑 在这种情况下自动选择 direct

**Comment by hkbase** [comment]
嗯，感谢您和各位开发者的辛苦付出，南无阿迷陀佛。

**Comment by vinograd-cyber** [comment]
学习了，感谢感谢！

**Comment by vinograd-cyber** [comment]
> @hkbase 你的结果是对的 感谢测试 下个版本会改进 vision 的逻辑 在这种情况下自动选择 direct

感谢您的帮助，我现在可以正常用vless+tls+vision了，因为我将客户端软件和中转之间的安全协议从xtls改成了tls，从而没再看到panic的触发复现。我觉得这块您 还可以再优化下，如果客户端用了xtls，可以在日志中打印错误提示，但主进程别发生panic中断退出比较好一些。

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-core/commit/1d7c40d7287545cdad368d43f563811a6ac088bc 修好了等待发布

**Comment by hkbase** [comment]
辛苦了～～感谢🙏

**Comment by hkbase** [comment]
我今天把仓库里的代码，自己编译后，测试了一下，一切工作正常，两个字：“完美”，自此新的vision流控，已经做到了自适应，非常感谢，特此回来汇报一下。
