### ISSUE TITLE
Server crash (GitHub Action Ver.43bc929)

### ISSUE THREAD

**Issue by testcaoy7** [XTLS/Xray-core#1722]
Version: 
Xray 1.7.5 (Xray, Penetrates Everything.) 43bc929 (go1.20.1 windows/amd64)
A unified platform for anti-censorship.

Issue:
Server only operates normally within few seconds, after few connections it will crash.

Configuration:
Standard "Vless + Reality + Vision + TCP", but with TCP Fast Open (TFO) enabled. ("sockopt": {"tcpFastOpen": true})

Log:
panic: extending out of bound

goroutine 167 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
	github.com/xtls/xray-core/common/buf/buffer.go:126
github.com/xtls/xray-core/proxy/vless/encoding.XtlsPadding(0xc0004e4510, 0x0, 0xc000266f38, 0x2?, {0x14b6920, 0xc00044b5c0})
	github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:559 +0x8a5
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
	github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:629 +0xa47
github.com/xtls/xray-core/common/task.Run.func1(0x12?)
	github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
	github.com/xtls/xray-core/common/task/task.go:27 +0xde

**Comment by yichya** [comment]
I saw this panic message on client side as well.

**Comment by picklefan** [comment]
今天早上拉的最新源码,自己编译的.
服务器Debian11 amd64 一小时蹦了两次, 自己的arm64 armbian, 到目前为止没有crash. 协议和上面一样
```
Feb 28 16:33:28 001 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 16:33:28 001 systemd[1]: xray.service: Failed with result 'exit-code'.
Feb 28 16:33:28 001 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Feb 28 16:33:28 001 systemd[1]: Stopped Xray Service.
Feb 28 16:33:28 001 systemd[1]: Started Xray Service.
Feb 28 16:33:28 001 xray[229460]: Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20.1 linux/amd64)
Feb 28 16:33:28 001 xray[229460]: A unified platform for anti-censorship.
Feb 28 16:33:28 001 xray[229460]: 2023/02/28 16:33:28 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 28 16:33:29 001 xray[229460]: panic: extending out of bound
Feb 28 16:33:29 001 xray[229460]: goroutine 74 [running]:
Feb 28 16:33:29 001 xray[229460]: github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
Feb 28 16:33:29 001 xray[229460]:         github.com/xtls/xray-core/common/buf/buffer.go:126
Feb 28 16:33:29 001 xray[229460]: github.com/xtls/xray-core/proxy/vless/encoding.XtlsPadding(0xc000af7cb0, 0x0, 0xc000240f38, 0x2?, {0x14b6920>
Feb 28 16:33:29 001 xray[229460]:         github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:559 +0x8a5
Feb 28 16:33:29 001 xray[229460]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
Feb 28 16:33:29 001 xray[229460]:         github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:629 +0xa47
Feb 28 16:33:29 001 xray[229460]: github.com/xtls/xray-core/common/task.Run.func1(0x12?)
Feb 28 16:33:29 001 xray[229460]:         github.com/xtls/xray-core/common/task/task.go:28 +0x2e
Feb 28 16:33:29 001 xray[229460]: created by github.com/xtls/xray-core/common/task.Run
Feb 28 16:33:29 001 xray[229460]:         github.com/xtls/xray-core/common/task/task.go:27 +0xde
Feb 28 16:33:29 001 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 16:33:29 001 systemd[1]: xray.service: Failed with result 'exit-code'.
Feb 28 16:33:29 001 systemd[1]: xray.service: Scheduled restart job, restart counter is at 6.
Feb 28 16:33:29 001 systemd[1]: Stopped Xray Service.
Feb 28 16:33:29 001 systemd[1]: xray.service: Start request repeated too quickly.
Feb 28 16:33:29 001 systemd[1]: xray.service: Failed with result 'exit-code'.
Feb 28 16:33:29 001 systemd[1]: Failed to start Xray Service.

```

**Comment by capxax** [comment]
一样，俩小时就崩一次

**Comment by RPRX** [comment]
现在 Vision 的 padding 有点小问题，等待 @yuhan6665 修复，在此之前，想用 REALITY 麻烦用上一个 commit 的版本 https://github.com/XTLS/Xray-core/commit/55dc26f22840c83045e6f34221533aa3cbe977a2

**Comment by yuhan6665** [comment]
感谢测试 麻烦试一下 https://github.com/XTLS/Xray-core/actions/runs/4304326723

**Comment by testcaoy7** [comment]
Limited testing indicates the bug was fixed. Thank you!

**Comment by testcaoy7** [comment]
@yuhan6665 I noticed a weird situation with 7b54255.

Version:
Xray 1.7.5 (Xray, Penetrates Everything.) 7b54255 (go1.20.1 windows/amd64)
A unified platform for anti-censorship.

Issue:
Client configuration has two local proxy inbound, one socks5 and another, HTTP.
Despite the fact that both proxy can be used in web browser to visit the web, Telegram connections can only be tunneled via socks5 proxy. When using HTTP proxy, telegram cannot connect to its server.

Configuration:
Standard "Vless + Reality + Vision + TCP". 

Log:
Everything normal. Client sent proxied connections to the server with a successful handshake, and server processed Vless protocol with Vision. The fact is there is no error at all. This is so weird. But Telegram only seems working under socks5 proxy with ver. 7b54255.

**Comment by yuhan6665** [comment]
@testcaoy7 can you show the full log when the issue happen with http proxy?

**Comment by testcaoy7** [comment]
#1728

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-core/actions/runs/4319767552

**Comment by testcaoy7** [comment]
@yuhan6665 Issue persists. (Ver. a479013)

**Comment by yuhan6665** [comment]
Fixed for http inbound. https://github.com/XTLS/Xray-core/actions/runs/4324509449
