### ISSUE TITLE
H2 服务端崩溃

### ISSUE THREAD

**Issue by rui0572** [XTLS/Xray-core#1748]
```
Xray 1.7.5 (Xray, Penetrates Everything.) c04c333 (go1.20.1 linux/amd64)
A unified platform for anti-censorship.
```

```
Mar 08 00:57:10 example.com xray[13310]: panic: Header called after Handler finished
Mar 08 00:57:10 example.com xray[13310]: goroutine 8090 [running]:
Mar 08 00:57:10 example.com xray[13310]: golang.org/x/net/http2.(*responseWriter).FlushError(0xc000be2fd8?)
Mar 08 00:57:10 example.com xray[13310]:         golang.org/x/net@v0.7.0/http2/server.go:2767 +0x119
Mar 08 00:57:10 example.com xray[13310]: golang.org/x/net/http2.(*responseWriter).Flush(0x484c45?)
Mar 08 00:57:10 example.com xray[13310]:         golang.org/x/net@v0.7.0/http2/server.go:2761 +0x19
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/transport/internet/http.flushWriter.Write({{0x7f8ec84af890?, 0xc000be2fd8?}, 0xc000c47518?}, {0xc00082c000, 0x2000, 0x2000})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/transport/internet/http/hub.go:56 +0xbf
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/buf.WriteMultiBuffer({0x144ad00, 0xc000c47548}, {0xc0000ec800?, 0xc00094dc38?, 0xc00094dbb8?})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/buf/multi_buffer.go:228 +0x103
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/buf.(*SequentialWriter).WriteMultiBuffer(0x4074e5?, {0xc0000ec800?, 0x38?, 0x40?})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/buf/writer.go:230 +0x38
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/net/cnc.(*connection).WriteMultiBuffer(0xc00008b4a0, {0xc0000ec800?, 0x38, 0x40})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/net/cnc/connection.go:122 +0x6f
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/buf.(*BufferedWriter).WriteMultiBuffer(0xc0002e5a40, {0xc0000ec800?, 0xc000b3d498?, 0xc00094dcf0?})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/buf/writer.go:144 +0x142
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/buf.copyInternal({0x1447d80, 0xc000b3d3e8}, {0x1446560, 0xc0002e5a40}, 0xc0003281b0)
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/buf/copy.go:87 +0x175
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/buf.Copy({0x1447d80, 0xc000b3d3e8}, {0x1446560, 0xc0002e5a40}, {0xc00094dec0, 0x1, 0x21?})
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/buf/copy.go:104 +0xa5
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:602 +0x70f
Mar 08 00:57:10 example.com xray[13310]: github.com/xtls/xray-core/common/task.Run.func1(0xc000b9c500?)
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/task/task.go:28 +0x2e
Mar 08 00:57:10 example.com xray[13310]: created by github.com/xtls/xray-core/common/task.Run
Mar 08 00:57:10 example.com xray[13310]:         github.com/xtls/xray-core/common/task/task.go:27 +0xde
Mar 08 00:57:10 example.com systemd[1]: xray@reality.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

服务端配置节选:

```
    "inbounds": [
        {
            "tag": "inbound-reality",
            "protocol": "vless",
            "port": 443,
            "settings": {
                "clients": [
                    {
                        "id": "test"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "h2",
                "security": "reality",
                "realitySettings": {
                    "xver": 2,
                    "dest": "/run/nginx.sock",
                    "serverNames": [
                        "example.com"
                    ],
                    "privateKey": "Lc5GP5-iNqs2hE_z8lAvXwUO9qv35taVcD2zLyfTAns",
                    "shortIds": [
                        ""
                    ]
                }
            }
        }
    ]
```

客户端配置节选:

```
    "outbounds": [
        {
            "tag": "outbound-reality",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "example.com",
                        "port": 443,
                        "users": [
                            {
                                "id": "test",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "h2",
                "security": "reality",
                "httpSettings": {
                    "read_idle_timeout": 25,
                    "health_check_timeout": 5
                },
                "realitySettings": {
                    "fingerPrint": "chrome",
                    "publicKey": "M7TFdjTFNWS6K2WkFzKLsX7no-b-aLv65VYXaP_AFF4",
                    "spiderX": "/"
                }
            }
        }
    ]
```

**Comment by RPRX** [comment]
~~终于有人为这个问题发 issue 了~~

`golang.org/x/net/http2` 的 `responseWriter` 实现得非常迷惑，一言不合就 panic，~~应该是 interface 的锅~~。而且外部不太好获取它的状态，即使先通过反射判断 `rws` 是否为 nil，也只能降低 panic 概率，因为同时存在多个协程，还是无法保证一定不 panic。

所以干脆加了个 recover()，请测试 https://github.com/XTLS/Xray-core/commit/836e84b8510a9478bc00dd8690cb71a51a607d11

**Comment by RPRX** [comment]
~~没关系，你还是可以测试的~~
