### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Mxy123h** [XTLS/Xray-core#180]
```
8:41888: write: broken pipe
panic: write tcp 127.0.0.1:1310->127.0.0.1:36206: write: broken pipe

goroutine 241851 [running]:
github.com/xtls/xray-core/common.Must(...)
        github.com/xtls/xray-core/common/common.go:26
github.com/xtls/xray-core/proxy/trojan.(*Server).handleUDPPayload.func1(0x10ad460, 0xc0006679c0, 0xc0008529c0)
        github.com/xtls/xray-core/proxy/trojan/server.go:259 +0xb4
github.com/xtls/xray-core/transport/internet/udp.handleInput(0x10ad460, 0xc0006679c0, 0xc0001ba8e0, 0x10ae960, 0xc0000cd778, 0x30000076c, 0xc0002b6bd0)
        github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:116 +0xb2
created by github.com/xtls/xray-core/transport/internet/udp.(*Dispatcher).getInboundRay
        github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:77 +0x550
root@kvmvps908-3jjmi:~/xray#

```

**Comment by Mxy123h** [comment]
用了2天 自动崩溃了

**Comment by rprx** [comment]
升级最新版本
