### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by zhj9709** [XTLS/Xray-core#193]
```
Jan 11 17:48:48 lt xray[1745]: panic: runtime error: slice bounds out of range [:-32]
Jan 11 17:48:48 lt xray[1745]: goroutine 84659459 [running]:
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf.(*Buffer).BytesTo(...)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf/buffer.go:113
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto.(*AuthenticationReader).readBuffer(0xc0564fef00, 0x2e00000007, 0x0, 0x0, 0x80)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto/auth.go:139 +0x33f
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto.(*AuthenticationReader).readInternal(0xc0564fef00, 0x0, 0xc00ce18d78, 0x0, 0x0)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto/auth.go:175 +0x125
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto.(*AuthenticationReader).ReadMultiBuffer(0xc0564fef00, 0xc05c78e680, 0x1, 0x10, 0x0, 0x0)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/crypto/auth.go:204 +0x85
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf.copyInternal(0x1096480, 0xc0564fef00, 0x10977c0, 0xc018b29770, 0xc04c2fc660, 0xc051e9b501, 0xc04c2fc640)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf/copy.go:81 +0x49
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf.Copy(0x1096480, 0xc0564fef00, 0x10977c0, 0xc018b29770, 0xc00ce18f38, 0x1, 0x1, 0x103000000000000, 0x3115c0043)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/proxy/vmess/inbound.(*Handler).Process.func1(0x0, 0x0)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:296 +0x147
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/task.OnSuccess.func1(0xc051e9b5f0, 0xfa0710)
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/task/task.go:12 +0x2f
Jan 11 17:48:48 lt xray[1745]: github.com/xtls/xray-core/common/task.
```

运行一段时间后panic了
1.2.0  1.2.1  1.2.2 都有这个问题
v2ray-core也有这个问题

**Comment by AkinoKaede** [comment]
应该是数组越界问题，能提供下配置文件（关键信息脱敏）吗？

**Comment by zhj9709** [comment]
> 应该是数组越界问题，能提供下配置文件（关键信息脱敏）吗？

https://github.com/v2fly/v2ray-core/issues/622

**Comment by zhj9709** [comment]
> 应该是数组越界问题，能提供下配置文件（关键信息脱敏）吗？

```javascript
    {
      "port": 18888,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxxx",
            "level": 1,
            "alterId": 16
          }
        ]
      },
      "streamSettings": {
        "security": "none",
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "path": "/"
            }
          }
        }
      }
    },
```

**Comment by rprx** [comment]
看样子很容易复现？

**Comment by zhj9709** [comment]
> 看样子很容易复现？

不止我一个人用，所以不知道具体什么场景会出现这种情况，但可能跟bt下载有关

**Comment by rprx** [comment]
改代码规避了这种情况 https://github.com/XTLS/Xray-core/commit/c880b916ee9866673a623e03ec743d6f81ad434b
