### ISSUE TITLE
[panic error] xray1.8.3使用shadowsocks连接udp时出现panic

### ISSUE THREAD

**Issue by GD-Slime** [XTLS/Xray-core#2252]
panic错误信息:
```
panic: extending out of bound

goroutine 65767 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
        github.com/xtls/xray-core/common/buf/buffer.go:126
github.com/xtls/xray-core/proxy/shadowsocks.(*AEADCipher).EncodePacket(0xc0001eccc0?, {0xc000a911e0?, 0xc0001eccc0?, 0x13aeec8?}, 0xc0001eccc0)
        github.com/xtls/xray-core/proxy/shadowsocks/config.go:178 +0x267
github.com/xtls/xray-core/proxy/shadowsocks.EncodeUDPPacket(0xc000b13e80, {0xc00077a000, 0x2000, 0x1?})
        github.com/xtls/xray-core/proxy/shadowsocks/protocol.go:231 +0x171
github.com/xtls/xray-core/proxy/shadowsocks.(*Server).handleUDPPayload.func1({0x13ada38, 0xc000def310}, 0xc000aa9580)
        github.com/xtls/xray-core/proxy/shadowsocks/server.go:101 +0x15e
github.com/xtls/xray-core/transport/internet/udp.handleInput({0x13ada38, 0xc000def310}, 0x440fc5?, {{0x13aeec8?, 0xc0008ecb50?}, 0x2300?, 0x0?}, 0xc0001970b0, 0xc000b13fb8?)
        github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:133 +0x2df
created by github.com/xtls/xray-core/transport/internet/udp.(*Dispatcher).getInboundRay
        github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:83 +0x6bb
```

服务端配置: xray 1.8.3, 除了shadowsocks外还开启了vless+reality(grpc)
<details>
</p>

```
{
	"log": {
		"loglevel": "warning"
	},
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"ip": [
					"geoip:cn",
					"geoip:private"
				],
				"outboundTag": "block"
			}
		]
	},
	"inbounds": [
		{
			"tag": "xray-script-xtls-reality",
			"listen": "0.0.0.0",
			"port": 443,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"email": "vless@xtls.reality",
						"id": "********************",
						"flow": "",
						"level": 0
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "grpc",
				"security": "reality",
				"realitySettings": {
					"show": false,
					"dest": "www.hkpm.org.hk:443",
					"xver": 0,
					"serverNames": [
						"www.hkpm.org.hk"
					],
					"privateKey": "*******************************",
					"shortIds": [
						""
					]
				},
				"grpcSettings": {
                    "serviceName": "*****"
                }
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls",
					"quic"
				]
			}
		},
		{
			"tag": "Origin",
			"port": *****,
			"protocol": "shadowsocks",
			"settings": {
				"method": "chacha20-ietf-poly1305",
				"password": "******************",
				"network": "tcp,udp"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls",
					"quic"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"tag": "IPv4_out"
		},
		{
			"tag": "IPv6_out",
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIPv6"
			}
		},
		{
			"protocol": "blackhole",
			"tag": "block"
		}
	]
}
```

</p>
</details>

客户端配置: passwall xray1.8.3 (配置里冗长的路由规则舍去了)

<details>

```
{
  "outbounds": [
    {
      "_flag_tag": "*******",
      "_flag_proxy": 0,
      "_flag_proxy_tag": "nil",
      "settings": {
        "servers": [
          {
            "password": "********",
            "port": *****,
            "method": "chacha20-poly1305",
            "address": "**************"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "sockopt": {
          "mark": 255
        }
      },
      "mux": {
        "enabled": false
      },
      "protocol": "shadowsocks",
      "tag": "default"
    },
    {
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blackhole"
    }
  ],
  "log": {
    "loglevel": "error"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": false,
        "statsUserDownlink": false
      }
    }
  },
  "routing": {
    "rules": [
		// some rules
      ]
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "hybrid"
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "domainsExcluded": [
          // some domains
        ],
        "destOverride": [
          "http",
          "tls"
        ],
        "metadataOnly": false
      },
      "settings": {
        "network": "udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "port": 1051,
      "protocol": "dokodemo-door",
      "tag": "udp_redir"
    }
  ]
}
```

</details>

看起来像是因为udp缓冲区数组越界? 我也不是太懂. 希望大佬能找出问题并修复.

**Comment by chika0801** [comment]
"method": "chacha20-ietf-poly1305",

你换成 2022-blake3-aes-128-gcm 这加密算法试试了？ 密码要用 openssl rand -base64 16 生成

**Comment by GD-Slime** [comment]
> "method": "chacha20-ietf-poly1305",
> 
> 你换成 2022-blake3-aes-128-gcm 这加密算法试试了？ 密码要用 openssl rand -base64 16 生成

这个panic是间歇性触发的, 我先用这个新加密算法试试吧.

**Comment by RPRX** [comment]
183 应该没动相关代码，测一下 182 有无该问题

**Comment by RPRX** [comment]
183 应该没动相关代码，测一下 181 有无该问题

**Comment by somebodywashere** [comment]
Ok this the same error (same log) starting to appear more frequently for me recently (yesterday it happened like four times in two hours). Usually it crashes once per 2-3-7 days (super random there). But I don't understand what's really causing it and it's pure random. Log is seems clear, also there's nothing shady in access.log prior to it.

**Comment by somebodywashere** [comment]
I'm actually using TCP+UDP so probably this problem is still with UDP right. I understand that this protocol not used much right now so there's not much info. But problem persists.

P.S. Trying 1.8.1 didn't help either.

**Comment by dog1912** [comment]
@somebodywashere @GD-Slime  Have you found where the problem is? I'm getting the same error: `goroutine 75214 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
	github.com/xtls/xray-core/common/buf/buffer.go:151
github.com/xtls/xray-core/proxy/shadowsocks.(*AEADCipher).EncodePacket(0xc01a2f2c00?, {0xc0019f6f00?, 0xc01a2f2c00?, 0x1657e78?}, 0xc01a2f2c00)
	github.com/xtls/xray-core/proxy/shadowsocks/config.go:192 +0x272
github.com/xtls/xray-core/proxy/shadowsocks.EncodeUDPPacket(0xc01d868e78, {0xc018e20000, 0x2000, 0xc01d868e80?})
	github.com/xtls/xray-core/proxy/shadowsocks/protocol.go:233 +0x15b
github.com/xtls/xray-core/proxy/shadowsocks.(*Server).handleUDPPayload.func1({0x1657d60, 0xc00b218b40}, 0xc0049902c0)
	github.com/xtls/xray-core/proxy/shadowsocks/server.go:121 +0x146
github.com/xtls/xray-core/transport/internet/udp.handleInput({0x1657d60, 0xc00b218b40}, 0x696750?, {{0x1657e78?, 0xc00cf460dc?}, 0xbfd0?, 0xc0?}, 0xc01b186e88, 0xc01815ad50?)
	github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:135 +0x22a
created by github.com/xtls/xray-core/transport/internet/udp.(*Dispatcher).getInboundRay in goroutine 76092
	github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:82 +0x56d`
