### ISSUE TITLE
panic: runtime error: index out of range [189] with length 127

### ISSUE THREAD

**Issue by MK0ltra** [XTLS/Xray-core#2478]
Xray v1.7.5 crash randomly. I think it's related to this weird url:
cdn.yektanet.comdl.google.comfarakav.com

```
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)

A unified platform for anti-censorship.

2023/08/13 13:31:25 [Info] infra/conf/serial: Reading config: bin/config.json

2023/08/13 13:31:25 [Warning] infra/conf: You are using an old version of XTLS, which is deprecated now and will be removed soon. Please use flow "xtls-rprx-vision" with "tls & tlsSettings" instead.

2023/08/13 13:31:25 [Warning] infra/conf: You are using an old version of XTLS, which is deprecated now and will be removed soon. Please use flow "xtls-rprx-vision" with "tls & tlsSettings" instead.

2023/08/23 08:07:46 [Info] [1434026520] proxy/vless/inbound: firstLen = 543

2023/08/23 08:07:46 [Info] [1434026520] proxy/vless/inbound: received request for tcp: UNKNOWN_IP_ADDRESS:9443

2023/08/23 08:07:46 [Info] [1434026520] app/dispatcher: sniffed domain: cdn.yektanet.comdl.google.comfarakav.com�`0 

panic: runtime error: index out of range [189] with length 127

goroutine 56851 [running]:

github.com/xtls/xray-core/common/strmatcher.(*ACAutomaton).Match(...)

github.com/xtls/xray-core/common/strmatcher/ac_automaton_matcher.go:228

github.com/xtls/xray-core/common/strmatcher.(*MphMatcherGroup).Match(0xc000c57e60, {0xc001102320, 0x42})

github.com/xtls/xray-core/common/strmatcher/mph_matcher.go:186 +0x39b

github.com/xtls/xray-core/app/router.(*DomainMatcher).ApplyDomain(0xc000c35d70, {0xc00069d480?, 0x123097f?})

github.com/xtls/xray-core/app/router/condition.go:102 +0x4a

github.com/xtls/xray-core/app/router.(*DomainMatcher).Apply(0xc000c527c8?, {0x13f6e18?, 0xc001868708?})

github.com/xtls/xray-core/app/router/condition.go:111 +0x4d

github.com/xtls/xray-core/app/router.(*ConditionChan).Apply(0xc00133bd10?, {0x13f6e18, 0xc001868708})

github.com/xtls/xray-core/app/router/condition.go:32 +0x6e

github.com/xtls/xray-core/app/router.(*Rule).Apply(...)

github.com/xtls/xray-core/app/router/config.go:63

github.com/xtls/xray-core/app/router.(*Router).pickRouteInternal(0xc00025be40, {0x13f6e18, 0xc001868708})

github.com/xtls/xray-core/app/router/router.go:94 +0x196

github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x13eeb40?, {0x13f6e18?, 0xc001868708?})

github.com/xtls/xray-core/app/router/router.go:72 +0x27

github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000117d40, {0x13eeb40, 0xc0010a1650}, 0xc000c43de0, {{0x13f0548, 0xc000576190}, 0x24e3, 0x2})

github.com/xtls/xray-core/app/dispatcher/default.go:452 +0x2bc

github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()

github.com/xtls/xray-core/app/dispatcher/default.go:323 +0x4c5

created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch

github.com/xtls/xray-core/app/dispatcher/default.go:304 +0x3dd
```

**Comment by RPRX** [comment]
v1.8.x 积累了很多修改，挺稳定的，你可以试试，这边也快发正式版了

**Comment by Johnny256Dawson** [comment]
@RPRX 动作要快，姿势要帅，麻溜的
