### ISSUE TITLE
panic: runtime error: slice bounds out of range [8184:8176]

### ISSUE THREAD

**Issue by shuangzhijinghua** [XTLS/Xray-core#2651]
program running at EPYC 7702 2 vCPU / 2GB memory / Ubuntu 22.04 x64, crash daily with 30k users and 70+ online users.
```
Oct 18 01:28:12 localhost XrayR[677]: panic: runtime error: slice bounds out of range [8184:8176]
Oct 18 01:28:12 localhost XrayR[677]: goroutine 25091839 [running]:
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/common/buf/buffer.go:128
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/proxy/vless/encoding.XtlsPadding(0xc006bab560, 0x2, 0x0, 0x2?, {0x39bfdb8, 0xc006822420})
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/proxy/vless/encoding/encoding.go:509 +0x89e
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/proxy/vless/encoding.XtlsWrite.func1({0x397f060, 0xc005834918}, 0xc0016fbc80, 0xc0016fbc70, 0xc0016fbc71, 0xc0016fbc72, 0x0?, 0x0?, {0x39bfdb8, 0xc006822420}, ...)
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/proxy/vless/encoding/encoding.go:341 +0x517
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/proxy/vless/encoding.XtlsWrite({0x397f060?, 0xc005834918?}, {0x3980d00, 0xc006822390}, {0x3980960?, 0xc006822150?}, {0x39cc630?, 0xc0058347c8?}, {0x0, 0x0}, ...)
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/proxy/vless/encoding/encoding.go:380 +0xd9
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/proxy/vless/inbound/inbound.go:599 +0x65d
Oct 18 01:28:12 localhost XrayR[677]: github.com/xtls/xray-core/common/task.Run.func1(0x12?)
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/common/task/task.go:28 +0x28
Oct 18 01:28:12 localhost XrayR[677]: created by github.com/xtls/xray-core/common/task.Run in goroutine 25091822
Oct 18 01:28:12 localhost XrayR[677]: #011github.com/xtls/xray-core@v1.8.4/common/task/task.go:27 +0xdb
```

**Comment by us254** [comment]
The error message you're seeing is a panic error in Go, which is a "stop-the-world" event related to the bounds of a slice. In your case, it seems like the program is trying to access the slice at an index that is out of its range.

The error is happening in the Extend function of the Buffer struct in the buf package of xray-core. This function is called by the XtlsPadding function in the encoding package of vless proxy.

This could be due to a bug in the XrayR program or it could be due to some unusual network conditions that the program isn't handling correctly.

**Comment by yuhan6665** [comment]
感谢报告 https://github.com/XTLS/Xray-core/commit/291061e9da6a5e1777f79c76e8c0859df8db821c 应该修复了 是一个比较难发现的边缘情况

**Comment by 50infivedays** [comment]
> 感谢报告 [291061e](https://github.com/XTLS/Xray-core/commit/291061e9da6a5e1777f79c76e8c0859df8db821c) 应该修复了 是一个比较难发现的边缘情况

@yuhan6665 hi~ 啥时候发新的发行版？我看最新的1.8.4还是有问题的

**Comment by Hare-W** [comment]
我也遇到了同样的问题，系统版本：Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)

**Comment by Fangliding** [comment]
Fixed

**Comment by hartois** [comment]
Same on Xray 26.2.6 (Xray, Penetrates Everything.) 12ee51e (go1.25.7 linux/amd64)

Crashing on 
```
newbuffer.Extend(paddingLen)
```

```
panic: runtime error: slice bounds out of range [230:200]

goroutine 144 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
	github.com/xtls/xray-core/common/buf/buffer.go:153
github.com/xtls/xray-core/proxy.XtlsPadding(0xb1ed2532780, 0x2, 0xb1ed234f008, 0x88?, {0x161c118, 0xb1ed2511680}, {0xb1ed299a120?, 0x4?, 0xb1ed24e6000?})
	github.com/xtls/xray-core/proxy/proxy.go:521 +0x6bb
github.com/xtls/xray-core/proxy.(*VisionWriter).WriteMultiBuffer(0xb1ed234efc0, {0xb1ed1efcfe0, 0x1, 0x1})
	github.com/xtls/xray-core/proxy/proxy.go:375 +0x4f4
github.com/xtls/xray-core/app/dispatcher.(*SizeStatWriter).WriteMultiBuffer(0xb1ed22d68e0, {0xb1ed1efcfe0, 0x1, 0x1})
	github.com/xtls/xray-core/app/dispatcher/stats.go:16 +0x6b
github.com/xtls/xray-core/proxy.CopyRawConnIfExist({0x161c150, 0xb1ed3bfa5a0}, {0x16285c8?, 0xb1ed1efcf78?}, {0x1628258, 0xb1ed2511530}, {0x1606e20, 0xb1ed22d68e0}, 0xb1ed260c880, 0x0)
	github.com/xtls/xray-core/proxy/proxy.go:773 +0x776
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process.func4()
	github.com/xtls/xray-core/proxy/freedom/freedom.go:221 +0x2a5
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process.OnSuccess.func7()
	github.com/xtls/xray-core/common/task/task.go:12 +0x22
github.com/xtls/xray-core/common/task.Run.func1(0xb1ed2510ba0?)
	github.com/xtls/xray-core/common/task/task.go:28 +0x28
created by github.com/xtls/xray-core/common/task.Run in goroutine 136
	github.com/xtls/xray-core/common/task/task.go:27 +0xdb

```

I'm up errors.LogDebug before newbuffer.Extend and got next before crash
```
2026/03/17 14:11:57.923286 [Debug] [1366970220] proxy: Xtls Unpadding new block, content 1503 padding 1 command 0
2026/03/17 14:11:57.923291 [Debug] [1366970220] proxy: XtlsFilterTls found tls client hello! 1109
2026/03/17 14:11:57.932340 [Debug] [1366970220] proxy: XtlsFilterTls found tls 1.3! 3910 TLS_CHACHA20_POLY1305_SHA256
2026/03/17 14:11:57.932391 [Debug] [1366970220] proxy: XtlsPadding 3910 276 0
2026/03/17 14:11:58.078248 [Debug] [1366970220] proxy: Xtls Unpadding new block, content 64 padding 887 command 0
2026/03/17 14:11:58.078304 [Debug] [1366970220] proxy: Xtls Unpadding new block, content 149 padding 1029 command 2
```
