### ISSUE TITLE
[Debug]添加了一个点，居然发生崩溃。

### ISSUE THREAD

**Issue by BI7PRK** [XTLS/Xray-core#2896]
```LOG
Fri Jan  5 09:27:34 2024 daemon.info xray[5933]: 2024/01/05 09:27:34 [Debug] transport/internet: dialing to tcp:*****:443
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: panic: runtime error: invalid memory address or nil pointer dereference
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ed888]
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]:
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: goroutine 595 [running]:
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: crypto/ecdh.(*PrivateKey).ECDH(0x1d1fb20?, 0x400130a640?)
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	crypto/ecdh/ecdh.go:127 +0x18
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/transport/internet/reality.UClient({0x13e39b0, 0x4000124628}, 0x40015b2f20, {0x13dcd38?, 0x4000769b00}, {{0x13dce88?, 0x4001306bc8?}, 0x5bc?, 0x0?})
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/transport/internet/reality/reality.go:140 +0x644
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/transport/internet/tcp.Dial({0x13dcd38, 0x4000769b00}, {{0x13dce88, 0x4001306bc8}, 0x8539, 0x2}, 0x4001643360)
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/transport/internet/tcp/dialer.go:34 +0x1d0
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/transport/internet.Dial({0x13dcd38, 0x4000769b00}, {{0x13dce88?, 0x4001306bc8?}, 0x6bc8?, 0x40?}, 0x400041a005?)
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/transport/internet/dialer.go:57 +0x1b0
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0x400130e500, {0x13dcd38?, 0x4000769b00?}, {{0x13dce88, 0x4001306bc8}, 0x8539, 0x2})
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:276 +0x908
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func1()
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:85 +0xac
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/common/retry.(*retryer).On(0x400062da60, 0x400062dac8)
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/common/retry/retry.go:27 +0xbc
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0x400027c150, {0x13dcd38, 0x4000769b00}, 0x40007a32c0, {0x13d3348?, 0x400130e500})
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:82 +0x1f8
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0x400130e500, {0x13dcd38, 0x4000769b00}, 0x40007a32c0)
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:206 +0x408
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0x40015c1f80, {0x13dcd38, 0x4000769b00}, 0x40007a32c0, {{0x13dcb08, 0x4000389740}, 0x1bb, 0x2})
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/app/dispatcher/default.go:443 +0xa3c
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/app/dispatcher/default.go:265 +0x538
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 594
Fri Jan  5 09:27:34 2024 daemon.err xray[5933]: 	github.com/xtls/xray-core/app/dispatcher/default.go:238 +0x38c
Fri Jan  5 09:27:34 2024 daemon.info procd: Instance xray_luci::xray.main s in a crash loop 9 crashes, 10 seconds since last crash
```

**Comment by BI7PRK** [comment]
问题在于：指纹选 **Android** 是发生 
` "security": "reality",`
`"fingerprint": "android"`

**Comment by Fangliding** [comment]
哪个点 麻烦提供配置(

**Comment by BI7PRK** [comment]
> 哪个点 麻烦提供配置(

protocol: **vless**
streamSettings.security: **reality**
streamSettings.realitySettings.fingerprint:**android**

**Comment by Fangliding** [comment]
用的api？

**Comment by BI7PRK** [comment]
![图片](https://github.com/XTLS/Xray-core/assets/24989210/35d7696b-8211-433c-8cbb-3c871ebd707a)

**Comment by yuhan6665** [comment]
fixed
