### ISSUE TITLE
java调用grpc接口时出错

### ISSUE THREAD

**Issue by maoxikun** [XTLS/Xray-core#2968]
1、config.json配置api相关
2、将proto编译成java代码（没问题）
编写java代码调用grpc接口如下：
```java
ManagedChannel channel = Grpc.newChannelBuilder("127.0.0.1:10085", InsecureChannelCredentials.create()).build();
        HandlerServiceGrpc.HandlerServiceBlockingStub handlerService = HandlerServiceGrpc.newBlockingStub(channel);
        StatsServiceGrpc.StatsServiceBlockingStub statsService = StatsServiceGrpc.newBlockingStub(channel);
        try {
            SysStatsResponse sysStatsResponse = statsService.getSysStats(SysStatsRequest.newBuilder().build());
            System.out.println(sysStatsResponse.getUptime());

            AlterInboundRequest alterInboundRequest = AlterInboundRequest.newBuilder()
                    .setTag("test")
                    .setTagBytes(RemoveUserOperation.newBuilder().setEmail("love@xray.com").build().toByteString())
                    .build();
            AlterInboundResponse alterInboundResponse = handlerService.alterInbound(alterInboundRequest);

            RemoveInboundResponse removeInboundResponse = handlerService.removeInbound(RemoveInboundRequest.newBuilder().setTag("test").build());

        } finally {
            channel.shutdown();
            try {
                channel.awaitTermination(5, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                logger.log(Level.parse("ERROR"), e.getMessage());
            }
        }
```
第一个接口getSysStats正常输出
第二个接口alterInbound报错如下：
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at com.xray.app.proxyman.command.HandlerServiceGrpc$HandlerServiceBlockingStub.alterInbound(HandlerServiceGrpc.java:406)
	at top.maoxikun.xray.controller.XrayController.main(XrayController.java:44)
```
服务端报错如下：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11d4057]

goroutine 33 [running]:
github.com/xtls/xray-core/common/serial.(*TypedMessage).GetInstance(0x0)
	github.com/xtls/xray-core/common/serial/typed_message.go:38 +0x17
github.com/xtls/xray-core/app/proxyman/command.(*handlerServer).AlterInbound(0xc000275bf0, {0x2046af0, 0xc0000ca7e0}, 0xc00014f2c0)
	github.com/xtls/xray-core/app/proxyman/command/command.go:83 +0x3e
github.com/xtls/xray-core/app/proxyman/command._HandlerService_AlterInbound_Handler({0x1d8f520?, 0xc000275bf0}, {0x2046af0, 0xc0000ca7e0}, 0xc0011ca080, 0x0)
	github.com/xtls/xray-core/app/proxyman/command/command_grpc.pb.go:194 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f49600, {0x2046af0, 0xc0000ca750}, {0x204ec20, 0xc000502340}, 0xc0002dc900, 0xc000275d10, 0x293c9d0, 0x0)
	google.golang.org/grpc@v1.60.1/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000f49600, {0x204ec20, 0xc000502340}, 0xc0002dc900)
	google.golang.org/grpc@v1.60.1/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.1/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 48
	google.golang.org/grpc@v1.60.1/server.go:1027 +0x115
```
请问是否能提供相关api的文档啊

**Comment by maoxikun** [comment]
调用方式错了，已解决
