### ISSUE TITLE
panic: runtime error: slice bounds out of range [8184:8176] 

### ISSUE THREAD

**Issue by Wfgukasha** [XTLS/Xray-core#3117]
### 发生错误之前做了什么

正常访问网站，偶尔遇到大流量的时候会报告以下panic错误

### 错误信息：

panic: runtime error: slice bounds out of range [8184:8176]

goroutine 7300 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
        github.com/xtls/xray-core/common/buf/buffer.go:128
github.com/xtls/xray-core/proxy/vless/encoding.XtlsPadding(0xc000796990, 0x2, 0x0, 0x2?, {0x13adae0, 0xc0005eda70})
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:505 +0x8ea
github.com/xtls/xray-core/proxy/vless/encoding.XtlsWrite.func1({0x13a0140, 0xc000012850}, 0xc0003a4490, 0xc0003a4224, 0xc0003a4225, 0xc0003a4226, 0x0?, 0x0?, {0x13adae0, 0xc0005eda70}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:337 +0x553
github.com/xtls/xray-core/proxy/vless/encoding.XtlsWrite({0x13a0140?, 0xc000012850?}, {0x139e940, 0xc0005ed9e0}, {0x139ee20?, 0xc0005ed8f0?}, {0x13b43c0?, 0xc000012780?}, {0x0, 0x0}, ...)
        github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:376 +0xe5
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
        github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:599 +0x6ab
github.com/xtls/xray-core/common/task.Run.func1(0xc000768cd0?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde

### 可能的解决方案

尝试通过增加切片大小来缓解，但可能治标不治本。也许可以通过将不需要的切片释放出去来让出空位？

**Comment by Wfgukasha** [comment]
目前好些了再观察一下情况
