### ISSUE TITLE
HTTPUpgrade直连panic异常退出

### ISSUE THREAD

**Issue by PHCSJC** [XTLS/Xray-core#3183]
版本1.8.9，服务器端x86_64，客户端斐讯N1，下载的arm64 v8，客户端异常退出：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18d640]

goroutine 54 [running]:
bufio.(*Writer).Flush(0x4000298a80)
	bufio/bufio.go:639 +0x40
net/http.(*Request).write(0x4000360000, {0x0, 0x0}, 0x0, 0x0, 0x0)
	net/http/request.go:764 +0x97c
net/http.(*Request).Write(...)
	net/http/request.go:555
github.com/xtls/xray-core/transport/internet/httpupgrade.dialhttpUpgrade({0x1067120, 0x40002763c0}, {{0x1066eb8, 0x4000402b90}, 0x1bc, 0x2}, 0x40002777c0)
	github.com/xtls/xray-core/transport/internet/httpupgrade/dialer.go:56 +0x794
github.com/xtls/xray-core/transport/internet/httpupgrade.dial({0x1067120, 0x40002763c0}, {{0x1066eb8, 0x4000402b90}, 0x1bc, 0x2}, 0x40002777c0)
	github.com/xtls/xray-core/transport/internet/httpupgrade/dialer.go:78 +0x14c
github.com/xtls/xray-core/transport/internet.Dial({0x1067120, 0x40002763c0}, {{0x1066eb8?, 0x4000402b90?}, 0x2b90?, 0x40?}, 0x0?)
	github.com/xtls/xray-core/transport/internet/dialer.go:60 +0x1a0
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0x400040c800, {0x1067120?, 0x40002763c0?}, {{0x1066eb8, 0x4000402b90}, 0x1bc, 0x2})
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:280 +0x7f4
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process.func1()
	github.com/xtls/xray-core/proxy/vmess/outbound/outbound.go:77 +0xac
github.com/xtls/xray-core/common/retry.(*retryer).On(0x400002de68, 0x400002de90)
	github.com/xtls/xray-core/common/retry/retry.go:27 +0xbc
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process(0x400040b260, {0x1067120, 0x40002763c0}, 0x40001581e0, {0x1064690, 0x400040c800})
	github.com/xtls/xray-core/proxy/vmess/outbound/outbound.go:75 +0x214
github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create.func1({0xffff7402a448, 0x400040b260}, {0x1064690, 0x400040c800}, {0x1057ca0, 0x400026a360})
	github.com/xtls/xray-core/common/mux/client.go:156 +0x16c
created by github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create in goroutine 27
	github.com/xtls/xray-core/common/mux/client.go:150 +0x1b4
```

服务器端配置：
```
{
  "inbounds": [
    {
      "port": 444,
      "listen": "0.0.0.0",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "aaaaaaa-aaaaa-aaaa-aaaaa-aaaaaaa",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {
          "acceptProxyProtocol": false,
          "path": "/",
          "host": "aa.bb.cc",
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置：
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1090,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
	  "tcpFastOpen": false,
          "tproxy": "redirect"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "aa.bb.cc",
            "port": 444,
            "users": [
              {
                "id": "aaaaaaa-aaaaa-aaaa-aaaaa-aaaaaaa",
                "alterId": 0
              }
            ]
          }
        ]
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {
          "acceptProxyProtocol": false,
          "path": "/",
          "host": "aa.bb.cc",
          "header": {
            "type": "none"
          }
        }
      }
    }
  ]
}
```

**Comment by Fangliding** [comment]
release里的httpupgrade要求开tls 下个版本会移除该要求

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/3128

**Comment by RPRX** [comment]
~~pin了pin了~~

**Comment by zhu327** [comment]
https://github.com/XTLS/Xray-core/blob/v1.8.9/transport/internet/httpupgrade/dialer.go#L49

https://xtls.github.io/config/transports/httpupgrade.html#httpupgradeobject

文档里面写了支持early data, 但是实际代码并没有实现

**Comment by Fangliding** [comment]
> https://github.com/XTLS/Xray-core/blob/v1.8.9/transport/internet/httpupgrade/dialer.go#L49
> 
> https://xtls.github.io/config/transports/httpupgrade.html#httpupgradeobject
> 
> 文档里面写了支持early data, 但是实际代码并没有实现

新版本才有 还没发布

**Comment by zhu327** [comment]
@Fangliding 在master分支还是没看到有 Sec-WebSocket-Protocol 相关的代码

**Comment by Fangliding** [comment]
@zhu327 没放在头里 实现不一样

**Comment by zhu327** [comment]
@Fangliding 理解了一下, 现在的实现是只要配置ed, 不管是多少, 都不等response回包, 直接写, 这样能过CDN吗

**Comment by Fangliding** [comment]
@zhu327 idk 所以多测一测啦()

**Comment by zhu327** [comment]
@Fangliding 我觉得是不行的, 因为CDN还没做到协议升级的处理, 所以我估计还是要回到 Sec-WebSocket-Protocol 的实现

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.10

**Comment by RPRX** [comment]
> @Fangliding 我觉得是不行的, 因为CDN还没做到协议升级的处理, 所以我估计还是要回到 Sec-WebSocket-Protocol 的实现

如果 CDN 遇到 HTTPUpgrade 就开始无条件双向转发是可以的，目前大家测的结果是能过 Cloudflare，~~但不能过 Caddy~~
