### ISSUE TITLE
使用go1.16编译无法启动服务端配置文件

### ISSUE THREAD

**Issue by hathlife** [XTLS/Xray-core#322]
已使用来自ubuntu backport源和openwrt 21.02分支的go1.16工具链均测试过，结果相同。
 ```
root@homerouter:~# ./xray-go1.16 --config=./xray-test.json
Xray 1.3.0 (Xray, Penetrates Everything.) OpenWrt (go1.16 linux/amd64)
A unified platform for anti-censorship.
2021/03/01 01:44:02 [Info] infra/conf/serial: Reading config: ./xray-test.json
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc0003d53b8, 0xc0000ae030, 0x16, 0x18, 0x16, 0x18)
        crypto/hmac/hmac.go:143 +0x370
github.com/xtls/xray-core/proxy/vmess/aead.KDF(0xc0003bddc0, 0x10, 0x10, 0xc0003d5420, 0x1, 0x1, 0x410418, 0x10, 0xd6ac20)
        github.com/xtls/xray-core/proxy/vmess/aead/kdf.go:13 +0x12f
github.com/xtls/xray-core/proxy/vmess/aead.KDF16(...)
        github.com/xtls/xray-core/proxy/vmess/aead/kdf.go:22
github.com/xtls/xray-core/proxy/vmess/aead.NewCipherFromKey(0xc0003bddc0, 0x10, 0x10, 0x0, 0x0)
        github.com/xtls/xray-core/proxy/vmess/aead/authid.go:41 +0x7c
github.com/xtls/xray-core/proxy/vmess/aead.NewAuthIDDecoder(...)
        github.com/xtls/xray-core/proxy/vmess/aead/authid.go:53
github.com/xtls/xray-core/proxy/vmess/aead.NewAuthIDDecoderItem(...)
        github.com/xtls/xray-core/proxy/vmess/aead/authid.go:84
github.com/xtls/xray-core/proxy/vmess/aead.(*AuthIDDecoderHolder).AddUser(0xc00030fa90, 0x8a14eac4d3fb19d8, 0xf385e25efb16d215, 0xd37e00, 0xc000354000)
        github.com/xtls/xray-core/proxy/vmess/aead/authid.go:90 +0x59
github.com/xtls/xray-core/proxy/vmess.(*TimedUserValidator).Add(0xc0003264d0, 0xc000354000, 0x0, 0x0)
        github.com/xtls/xray-core/proxy/vmess/validator.go:150 +0x1fc
github.com/xtls/xray-core/proxy/vmess/inbound.(*Handler).AddUser(0xc00032c3c0, 0x1020c60, 0xc000319da0, 0xc000354000, 0xc00024f1c0, 0x5a614c83063e328)
        github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:164 +0x45
github.com/xtls/xray-core/proxy/vmess/inbound.New(0x1020c60, 0xc000319da0, 0xc0003015c0, 0x8500000000000000, 0x3, 0xc0001a2700)
        github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:131 +0x3c5
github.com/xtls/xray-core/proxy/vmess/inbound.init.1.func1(0x1020c60, 0xc000319da0, 0xe730e0, 0xc0003015c0, 0x1, 0x4d, 0x102c5c8, 0xc0003015c0)
        github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:362 +0x54
github.com/xtls/xray-core/common.CreateObject(0x1020c60, 0xc000319da0, 0xe730e0, 0xc0003015c0, 0x0, 0x0, 0x0, 0x102c5c8)
        github.com/xtls/xray-core/common/type.go:32 +0x22d
github.com/xtls/xray-core/app/proxyman/inbound.NewAlwaysOnInboundHandler(0x1020c60, 0xc000319da0, 0x0, 0x0, 0xc000326460, 0xe730e0, 0xc0003015c0, 0x203000, 0xda6460, 0x0)
        github.com/xtls/xray-core/app/proxyman/inbound/always.go:52 +0x6a
github.com/xtls/xray-core/app/proxyman/inbound.NewHandler(0x1020c60, 0xc000319da0, 0xc000311720, 0x91c4c85bd8033101, 0x91007fbc45fcbda8, 0x0, 0xc0001a27d0)
        github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:162 +0x150
github.com/xtls/xray-core/app/proxyman/inbound.init.0.func2(0x1020c60, 0xc000319da0, 0xe58c20, 0xc000311720, 0xc00020d901, 0x410418, 0x30, 0xe63a00)
        github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:176 +0x54
github.com/xtls/xray-core/common.CreateObject(0x1020c60, 0xc000319da0, 0xe58c20, 0xc000311720, 0xe1c940, 0xc000311ef0, 0x1020c60, 0xc000319da0)
        github.com/xtls/xray-core/common/type.go:32 +0x22d
github.com/xtls/xray-core/core.CreateObject(0xc000311ef0, 0xe58c20, 0xc000311720, 0x7fbb45da80c0, 0xc00024f1c0, 0x1, 0x0)
        github.com/xtls/xray-core/core/functions.go:20 +0x55
github.com/xtls/xray-core/core.AddInboundHandler(0xc000311ef0, 0xc000311720, 0x4, 0xdacc20)
        github.com/xtls/xray-core/core/xray.go:100 +0xa5
github.com/xtls/xray-core/core.addInboundHandlers(0xc000311ef0, 0xc0000b5330, 0x1, 0x1, 0x0, 0x1)
        github.com/xtls/xray-core/core/xray.go:116 +0x56
github.com/xtls/xray-core/core.initInstanceWithConfig(0xc000231710, 0xc000311ef0, 0x40d7b9, 0x18, 0xd85080)
        github.com/xtls/xray-core/core/xray.go:230 +0x4f6
github.com/xtls/xray-core/core.New(0xc000231710, 0x4, 0xd7d760, 0xc0000c5ea8)
        github.com/xtls/xray-core/core/xray.go:163 +0x77
main.startXray(0x454faf, 0xc000214300, 0xc000214180, 0x164)
        github.com/xtls/xray-core/main/run.go:178 +0x2ae
main.executeRun(0x14fb000, 0xc0001e78b0, 0x0, 0x1)
        github.com/xtls/xray-core/main/run.go:67 +0x4a
github.com/xtls/xray-core/main/commands/base.Execute()
        github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x285
main.main()
        github.com/xtls/xray-core/main/main.go:22 +0x16e
root@homerouter:~#
```

**Comment by JimhHan** [comment]
请使用main分支
