### ISSUE TITLE
负载均衡策略 leastPing 和 leastLoad 出现报错

### ISSUE THREAD

**Issue by ramondsq** [XTLS/Xray-core#3241]
问题：负载均衡的策略使用`leastPing`和`leastLoad`时均会出现如下报错，但是使用`random`或`roundRobin`则不会。

版本：Xray 1.8.10

平台：Windows 11 直接下载的最新 release 中的二进制文件，macOS 通过 brew 安装

简化配置如下：
```
{
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "domain": [
                    "geosite:cn",
                    "geosite:private"
                ],
                "outboundTag": "direct"
            },
            {
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct"
            },
            {
                "domain": [
                    "geosite:geolocation-!cn"
                ],
                "balancerTag": "balancer"
            }
        ],
        "balancers": [
            {
                "selector": [
                    "do"
                ],
                "strategy": {
                    "type": "leastPing"
                },
                "tag": "balancer"
            }
        ]
    },
    "outbounds": [
        {
            "tag": "do1"
        },
        {
            "tag": "do2"
        },
        {
            "tag": "do3"
        },
        {
            "tag": "do4"
        },
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}
```

运行日志如下：
```
2024/04/06 14:36:26 [Info] [3262371171] proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2024/04/06 14:36:26 [Info] [3262371171] app/dispatcher: sniffed domain: www.google.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x132c308]

goroutine 43 [running]:
github.com/xtls/xray-core/app/router.(*LeastPingStrategy).PickOutbound(0xc00029c3e0?, {0xc0002592c0, 0x4, 0x6?})
        github.com/xtls/xray-core/app/router/strategy_leastping.go:33 +0xa8
github.com/xtls/xray-core/app/router.(*Balancer).PickOutbound(0xc000164af0)
        github.com/xtls/xray-core/app/router/balancing.go:60 +0x1f7
github.com/xtls/xray-core/app/router.(*Rule).GetTag(...)
        github.com/xtls/xray-core/app/router/config.go:21
github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x1c0e7c0?, {0x1c177d0?, 0xc0003300d8?})
        github.com/xtls/xray-core/app/router/router.go:87 +0x5a
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0000daea0, {0x1c0e7c0, 0xc00028b590}, 0xc00012eb40, {{0x1c0e5c8, 0xc000342540}, 0x1bb, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:403 +0x2e2
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/xtls/xray-core/app/dispatcher/default.go:266 +0x3f9
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 42
        github.com/xtls/xray-core/app/dispatcher/default.go:239 +0x40b
```

**Comment by ramondsq** [comment]
没有配置`observatory`
