### ISSUE TITLE
burstObservatory panic

### ISSUE THREAD

**Issue by unidcml** [XTLS/Xray-core#3920]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I am using Xray-core v24.9.30 on OpenWrt 23.05.5.

Omitting ```pingConfig``` in ```BurstObservatoryObject```
```json
"burstObservatory": {
  "subjectSelector": ["reality"],
  "pingConfig": {}
}
```
results panic in logs
```
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xea7694]
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: goroutine 1 [running]:
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: github.com/xtls/xray-core/infra/conf.BurstObservatoryConfig.Build(...)
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/infra/conf/observatory.go:29
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: github.com/xtls/xray-core/infra/conf.(*Config).Build(0x4000133b90)
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/infra/conf/xray.go:582 +0xb04
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: github.com/xtls/xray-core/infra/conf/serial.BuildConfig({0x40001814a0?, 0x0?, 0x400015bc18?})
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/infra/conf/serial/builder.go:52 +0x38
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: github.com/xtls/xray-core/core.LoadConfig({0x120a3d8, 0x4}, {0xfc4440?, 0x400000fd88?})
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/core/config.go:148 +0x530
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: main.startXray()
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/main/run.go:219 +0x9c
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: main.executeRun(0x1c66c40?, {0x400003c0a0?, 0x400015bdf8?, 0x44be64?})
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/main/run.go:77 +0x4c
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: github.com/xtls/xray-core/main/commands/base.Execute()
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x568
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]: main.main()
Wed Oct 16 18:43:01 2024 daemon.err xray[5490]:         github.com/xtls/xray-core/main/main.go:22 +0x1a0
```

### Reproduction Method

-

### Client config

<details><pre><code>
-
</code></pre></details>

### Server config

<details><pre><code>
-
</code></pre></details>

### Client log

<details><pre><code>
-
</code></pre></details>

### Server log

<details><pre><code>
-
</code></pre></details>

**Comment by Fangliding** [comment]
`"pingConfig": {}` needs valid field
