### ISSUE TITLE
panic: extending out of bound 

### ISSUE THREAD

**Issue by morrisae** [XTLS/Xray-core#4074]
```
panic: extending out of bound

goroutine 5835 [running]:

github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)

github.com/xtls/xray-core/common/buf/buffer.go:127

github.com/xtls/xray-core/proxy/shadowsocks.(*AEADCipher).EncodePacket(0xc0012d1c50?, {0xc0013d1900?, 0xc0012d1c50?, 0x154cb98?}, 0xc0012d1c50)

github.com/xtls/xray-core/proxy/shadowsocks/config.go:192 +0x232

github.com/xtls/xray-core/proxy/shadowsocks.EncodeUDPPacket(0xc002255e78, {0xc0014a200a, 0x1fec, 0xc002255e80?})

github.com/xtls/xray-core/proxy/shadowsocks/protocol.go:233 +0x15b

github.com/xtls/xray-core/proxy/shadowsocks.(*Server).handleUDPPayload.func1({0x154ca80, 0xc00159a5a0}, 0xc0018fa880)

github.com/xtls/xray-core/proxy/shadowsocks/server.go:121 +0x146

github.com/xtls/xray-core/transport/internet/udp.handleInput({0x154ca80, 0xc00159a5a0}, 0xc0018925b0?, {{0x154cb98?, 0xc0004691dc?}, 0x2fd0?, 0xc0?}, 0xc001971968, 0xc000792fa0?)

github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:135 +0x22a

created by github.com/xtls/xray-core/transport/internet/udp.(*Dispatcher).getInboundRay in goroutine 5830

github.com/xtls/xray-core/transport/internet/udp/dispatcher.go:82 +0x55d 
```

**Comment by Fangliding** [comment]
模板

**Comment by morrisae** [comment]
服务器上运行有2个内核。 核心1与传入shadowsocks传出袜子（从核心2），核心2传入袜子传出wireguard平衡

**Comment by Fangliding** [comment]
简单的描述没用 按要求填写模板不然很难处理问题

**Comment by morrisae** [comment]
您可以链接到模板

**Comment by Fangliding** [comment]
不再赘述 请按模板新开或者编辑
