### ISSUE TITLE
XHTTP `downloadsettings` 遗漏 `network` 导致 `panic: interface conversion: interface {} is *tcp.Config, not *splithttp.Config`

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#4117]
```golang
panic: interface conversion: interface {} is *tcp.Config, not *splithttp.Config
goroutine 46 [running]:
github.com/xtls/xray-core/transport/internet/splithttp.getHTTPClient({0x154e418, 0xc0001889c0}, {{0x154e0d0?, 0xc00012a9f0?}, 0x3?, 0xc0?}, 0xc00008cba0)
        github.com/xtls/xray-core/transport/internet/splithttp/dialer.go:69 +0x4f4
github.com/xtls/xray-core/transport/internet/splithttp.Dial({0x154e418, 0xc0001889c0}, {{0x154e0d0, 0xc00012b3d0}, 0x1bb, 0x2}, 0xc0004168a0)
        github.com/xtls/xray-core/transport/internet/splithttp/dialer.go:282 +0x6d1
github.com/xtls/xray-core/transport/internet.Dial({0x154e418, 0xc0001889c0}, {{0x154e0d0?, 0xc00012b3d0?}, 0xb3d0?, 0xc0?}, 0xc00044e370?)
        github.com/xtls/xray-core/transport/internet/dialer.go:61 +0x168
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc001244280, {0x154e418, 0xc0001889c0}, {{0x154e0d0, 0xc00012b3d0}, 0x1bb, 0x2})
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:287 +0x974
github.com/xtls/xray-core/proxy/trojan.(*Client).Process.func1()
        github.com/xtls/xray-core/proxy/trojan/client.go:68 +0xa6
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc000489cc8, 0xc000489ce8)
        github.com/xtls/xray-core/common/retry/retry.go:27 +0xc6
github.com/xtls/xray-core/proxy/trojan.(*Client).Process(0xc00124a1c0, {0x154e418, 0xc0001889c0}, 0xc00124a640, {0x154b760, 0xc001244280})
        github.com/xtls/xray-core/proxy/trojan/client.go:66 +0x239
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc001244280, {0x154e418, 0xc0001889c0}, 0xc00124a640)
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x388
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000416d80, {0x154e418, 0xc0001889c0}, 0xc00124a640, {{0x154e0d0, 0xc00012bef0}, 0x50, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:481 +0xc26
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 45
        github.com/xtls/xray-core/app/dispatcher/default.go:268 +0x56c
```
```json
{
  "tag": "s1-out",
  "protocol": "Trojan",
  "settings": {
    "servers": [
      {
        "#address": "unpkg.com",
        "address": "s1.*.net",
        "port": 443,
        "password": "*"
      }
    ]
  },
  "streamSettings": {
    "network": "xhttp",
    "grpcSettings": {
      "serviceName": "*",
      "multiMode": true
    },
    "xhttpSettings": {
      "path": "/*",
      "mode": "stream-up",
      "keepAlivePeriod": -1,
      "xPaddingBytes": -1,
      "downloadSettings": {
        "address": "s1.*.net",
        "port": 443,
        "xhttpSettings": {
          "path": "/*",
          "mode": "stream-up",
          "keepAlivePeriod": -1,
          "xPaddingBytes": -1
        },
        "security": "tls",
        "tlsSettings": {
          "enableSessionResumption": true
        },
        "sockopt": {
          "TCPUserTimeout": 15000,
          "tcpFastOpen": true,
          "TcpKeepAliveIdle": 300,
          "domainStrategy": "UseIPv4"
        }
      }
    },
    "security": "tls",
    "tlsSettings": {
      "#serverName": "s1.*.net",
      "enableSessionResumption": true,
      "alpn": [
        "h3"
      ]
    },
    "#sockopt": {
      "TCPUserTimeout": 15000,
      "tcpFastOpen": true,
      "TcpKeepAliveIdle": 300,
      "domainStrategy": "UseIPv4"
    }
  }
}
```
>```json
>        "port": 443,
>        "xhttpSettings": {
>```

`network` ?

https://t.me/projectXray/4102138?thread=4031009

**Comment by xqzr** [comment]
`xray -test` 测试可通过

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/discussions/4113

> 显然其中 `network` 必须为 "xhttp"

**Comment by Fangliding** [comment]
加一个为空自动写入xhttp或者写其他的自动报错也是可以考虑的

**Comment by RPRX** [comment]
> 加一个为空自动写入xhttp或者写其他的自动报错也是可以考虑的

~~panic 也是报错的一种~~
