### ISSUE TITLE
上下行分离xhttp使用时发生panic

### ISSUE THREAD

**Issue by zhangsan946** [XTLS/Xray-core#4125]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

xray服务过几分钟就会无法连接，查看systlog发现xray有panic。
```
Dec  6 10:38:57 jp3 xray[3775703]: Xray 24.11.30 (Xray, Penetrates Everything.) 98a72b6 (go1.23.3 linux/arm64)
Dec  6 10:38:57 jp3 xray[3775703]: A unified platform for anti-censorship.
Dec  6 10:38:57 jp3 xray[3775703]: 2024/12/06 10:38:57 [Info] infra/conf/serial: Reading config: &{Name:/opt/xray/config.json Format:json}
Dec  6 10:38:59 jp3 xray[3775703]: panic: runtime error: invalid memory address or nil pointer dereference
Dec  6 10:38:59 jp3 xray[3775703]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x83a004]
Dec  6 10:38:59 jp3 xray[3775703]: goroutine 66 [running]:
Dec  6 10:38:59 jp3 xray[3775703]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func2()
Dec  6 10:38:59 jp3 xray[3775703]: #011github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:360 +0xe4
Dec  6 10:38:59 jp3 xray[3775703]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.OnSuccess.func8()
Dec  6 10:38:59 jp3 xray[3775703]: #011github.com/xtls/xray-core/common/task/task.go:12 +0x30
Dec  6 10:38:59 jp3 xray[3775703]: github.com/xtls/xray-core/common/task.Run.func1(0x400018fa40?)
Dec  6 10:38:59 jp3 xray[3775703]: #011github.com/xtls/xray-core/common/task/task.go:28 +0x34
Dec  6 10:38:59 jp3 xray[3775703]: created by github.com/xtls/xray-core/common/task.Run in goroutine 52
Dec  6 10:38:59 jp3 xray[3775703]: #011github.com/xtls/xray-core/common/task/task.go:27 +0xd0
Dec  6 10:38:59 jp3 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec  6 10:38:59 jp3 systemd[1]: xray.service: Failed with result 'exit-code'.
Dec  6 10:38:59 jp3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 18.
Dec  6 10:38:59 jp3 systemd[1]: Stopped xray Service.
```

### 重现方式

上下行分离xhttp，上行vless+tls+cdn，下行vless+reality+直连， 访问网页时不时就会发生。

### 客户端配置

```
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "tag": "in",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "cdn-domain.com",
            "port": 443,
            "users": [
              {
                "id": "uuid",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "xhttp",
        "security": "tls",
        "xhttpSettings": {
          "path": "/test",
          "mode": "auto",
          "extra": {
            "downloadSettings": {
              "address": "direct-domain.com",
              "port": 8443,
              "network": "xhttp",
              "xhttpSettings": {
                "path": "/test"
              },
              "security": "reality",
              "realitySettings": {
                "fingerprint": "chrome",
                "serverName": "www.lovelive-anime.jp",
                "publicKey": "pbk",
                "shortId": "sid"
              }
            }
          }
        },
        "tlsSettings": {
          "alpn": [
            "h2"
          ],
          "fingerprint": "chrome"
        }
      }
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blocked"
    }
  ],
  "dns": {
    "servers": [
      "1.1.1.1",
      {
        "address": "114.114.114.114",
        "port": 53,
        "domains": [
          "geosite:cn"
        ]
      },
      "8.8.8.8",
      "8.8.4.4"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:geolocation-!cn"
        ],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
```

### 服务端配置

```
{
    "log": {
        "loglevel": "debug",
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log"
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1111,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
                        "level": 1,
                        "email": "uuid@mail.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "8001",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "8002",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "path": "/ws"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "tag": "wstag"
        },
{
            "listen": "127.0.0.1",
            "port": 2222,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "clients": [
                    {
                        "id": "uuid",
                        "level": 1,
                        "email": "uuid@mail.com"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": "8001",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "8002",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "xhttpSettings": {
                    "path": "/test"
                }
            },
            "tag": "xhttptag"
        },
        {
            "listen": "0.0.0.0",
            "port": 8443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 2222
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "target": "www.lovelive-anime.jp:443",
                    "serverNames": [
                        "www.lovelive-anime.jp"
                    ],
                    "privateKey": "pvk",
                    "shortIds": [
                        "sid"
                    ]
                }
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 3333,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "blocked"
        }
    ],
    "api": {
        "tag": "api",
        "services": [
            "HandlerService",
            "StatsService"
        ]
    },
    "stats":{
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api"
            },
            {
                "type": "field",
                "domain": [
                    "fonts.gstatic.com",
                    "fonts.googleapis.com"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            }
        ]
    },
            "policy": {
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true
        },
        "levels": {
            "1": {
                "statsUserUplink": true,
                "statsUserDownlink": true,
                "handshake": 3,
                "connIdle": 180
            }
        }
    }
}
```

### 客户端日志

 -

### 服务端日志

```
2024/12/06 10:47:02 [Warning] core: Xray 24.11.30 started
2024/12/06 10:47:02 [Debug] [3892288479] proxy/dokodemo: processing connection from: 127.0.0.1:56384
2024/12/06 10:47:02 [Info] [3892288479] proxy/dokodemo: received request for 127.0.0.1:56384
2024/12/06 10:47:02 [Info] [3892288479] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2024/12/06 10:47:03 [Info] [498448785] proxy/vless/inbound: firstLen = 70
2024/12/06 10:47:03 [Info] [498448785] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/12/06 10:47:03 [Info] [498448785] proxy/vless/inbound: realName = www.lovelive-anime.jp
2024/12/06 10:47:03 [Info] [498448785] proxy/vless/inbound: realAlpn = 
2024/12/06 10:47:04 [Info] [3897393330] proxy/vless/inbound: firstLen = 1360
2024/12/06 10:47:04 [Info] [3897393330] proxy/vless/inbound: received request for tcp:alive.github.com:443
2024/12/06 10:47:04 [Debug] app/stats: create new counter user>>>uuid@mail.com>>>traffic>>>uplink
2024/12/06 10:47:04 [Debug] app/stats: create new counter user>>>uuid@mail.com>>>traffic>>>downlink
2024/12/06 10:47:04 [Info] [3897393330] app/dispatcher: default route for tcp:alive.github.com:443
2024/12/06 10:47:04 [Info] [3897393330] transport/internet/tcp: dialing TCP to tcp:alive.github.com:443
2024/12/06 10:47:04 [Debug] [3897393330] transport/internet: dialing to tcp:alive.github.com:443
2024/12/06 10:47:04 [Info] [789391742] proxy/vless/inbound: firstLen = 1291
2024/12/06 10:47:04 [Info] [789391742] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [789391742] app/dispatcher: default route for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [789391742] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/12/06 10:47:04 [Debug] [789391742] transport/internet: dialing to tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [789391742] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 10.0.0.213:51054, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [789391742] proxy: CopyRawConn readv
2024/12/06 10:47:04 [Info] [3503144244] proxy/vless/inbound: firstLen = 1825
2024/12/06 10:47:04 [Info] [3503144244] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [3503144244] app/dispatcher: default route for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [3503144244] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/12/06 10:47:04 [Debug] [3503144244] transport/internet: dialing to tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [3503144244] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 10.0.0.213:51064, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [3503144244] proxy: CopyRawConn readv
2024/12/06 10:47:04 [Info] [1797935072] proxy/vless/inbound: firstLen = 2342
2024/12/06 10:47:04 [Info] [1797935072] proxy/vless/inbound: received request for tcp:optimizationguide-pa.googleapis.com:443
2024/12/06 10:47:04 [Info] [1797935072] app/dispatcher: default route for tcp:optimizationguide-pa.googleapis.com:443
2024/12/06 10:47:04 [Info] [1797935072] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2024/12/06 10:47:04 [Debug] [1797935072] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2024/12/06 10:47:04 [Info] [1797935072] proxy/freedom: connection opened to tcp:optimizationguide-pa.googleapis.com:443, local endpoint 10.0.0.213:12412, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [1797935072] proxy: CopyRawConn readv
2024/12/06 10:47:04 [Info] [3897393330] proxy/freedom: connection opened to tcp:alive.github.com:443, local endpoint 10.0.0.213:19584, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [3897393330] proxy: CopyRawConn readv
2024/12/06 10:47:04 [Info] [2340000927] proxy/vless/inbound: firstLen = 1761
2024/12/06 10:47:04 [Info] [2340000927] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [894489262] proxy/vless/inbound: firstLen = 1817
2024/12/06 10:47:04 [Info] [894489262] proxy/vless/inbound: received request for tcp:waa-pa.clients6.google.com:443
2024/12/06 10:47:04 [Info] [2340000927] app/dispatcher: default route for tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [2340000927] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/12/06 10:47:04 [Debug] [2340000927] transport/internet: dialing to tcp:www.google.com:443
2024/12/06 10:47:04 [Info] [894489262] app/dispatcher: default route for tcp:waa-pa.clients6.google.com:443
2024/12/06 10:47:04 [Info] [894489262] transport/internet/tcp: dialing TCP to tcp:waa-pa.clients6.google.com:443
2024/12/06 10:47:04 [Debug] [894489262] transport/internet: dialing to tcp:waa-pa.clients6.google.com:443
2024/12/06 10:47:04 [Info] [2340000927] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 10.0.0.213:51078, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [2340000927] proxy: CopyRawConn readv
2024/12/06 10:47:04 [Info] [894489262] proxy/freedom: connection opened to tcp:waa-pa.clients6.google.com:443, local endpoint 10.0.0.213:59266, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:04 [Info] [894489262] proxy: CopyRawConn readv
2024/12/06 10:47:05 [Info] [2885877539] proxy/vless/inbound: firstLen = 1801
2024/12/06 10:47:05 [Info] [2885877539] proxy/vless/inbound: received request for tcp:alive.github.com:443
2024/12/06 10:47:05 [Info] [2885877539] app/dispatcher: default route for tcp:alive.github.com:443
2024/12/06 10:47:05 [Info] [2885877539] transport/internet/tcp: dialing TCP to tcp:alive.github.com:443
2024/12/06 10:47:05 [Debug] [2885877539] transport/internet: dialing to tcp:alive.github.com:443
2024/12/06 10:47:05 [Info] [2885877539] proxy/freedom: connection opened to tcp:alive.github.com:443, local endpoint 10.0.0.213:55158, remote endpoint xxx.xxx.xxx.xxx:443
2024/12/06 10:47:05 [Info] [2885877539] proxy: CopyRawConn readv
2024/12/06 10:47:05 [Info] [3491341393] proxy/vless/inbound: firstLen = 70
2024/12/06 10:47:05 [Info] [3491341393] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/12/06 10:47:05 [Info] [3491341393] proxy/vless/inbound: realName = www.lovelive-anime.jp
2024/12/06 10:47:05 [Info] [3491341393] proxy/vless/inbound: realAlpn = 
2024/12/06 10:47:05 [Info] [586102076] proxy/vless/inbound: firstLen = 0
2024/12/06 10:47:05 [Info] [586102076] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/12/06 10:47:05 [Debug] app/log: Logger started
2024/12/06 10:47:05 [Debug] app/router: MphDomainMatcher is enabled for 2 domain rule(s)
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>wstag>>>traffic>>>uplink
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>wstag>>>traffic>>>downlink
2024/12/06 10:47:05 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1111
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>xhttptag>>>traffic>>>uplink
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>xhttptag>>>traffic>>>downlink
2024/12/06 10:47:05 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2222
2024/12/06 10:47:05 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:8443
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>uplink
2024/12/06 10:47:05 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>downlink
2024/12/06 10:47:05 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:3333
2024/12/06 10:47:05 [Info] transport/internet/websocket: listening TCP(for WS) on 127.0.0.1:1111
2024/12/06 10:47:05 [Info] transport/internet/splithttp: listening TCP(for SH) on 127.0.0.1:2222
2024/12/06 10:47:05 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:3333
2024/12/06 10:47:05 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:8443
2024/12/06 10:47:05 [Warning] core: Xray 24.11.30 started
```

**Comment by RPRX** [comment]
> localAddr, localPort, err := net.SplitHostPort(connection.LocalAddr().String())

看起来是 connection.LocalAddr() 返回了 nil，不过这监听公网的 REALITY 取 LocalAddr() 咋会返回 nil

**Comment by RPRX** [comment]
不是 REALITY 的问题，是 XHTTP 的 VLESS 内不能写 fallbacks，目前没给 localAddr 赋值：

https://github.com/XTLS/Xray-core/blob/46d8d9ef02f61ac22c629a3fc7373b20c13c2608/transport/internet/splithttp/hub.go#L238-L246
