### ISSUE TITLE
panic: close of closed channel(github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...))

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#4148]
```golang
panic: close of closed channel

goroutine 2655 [running]:
github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...)
  github.com/quic-go/quic-go@v0.46.0/http3/body.go:124
github.com/quic-go/quic-go/http3.(*hijackableBody).Close(0xc000df0720)
  github.com/quic-go/quic-go@v0.46.0/http3/body.go:130 +0x2b
github.com/xtls/xray-core/transport/internet/splithttp.(*WaitReadCloser).Close(0x180a2b8?)
  github.com/xtls/xray-core/transport/internet/splithttp/client.go:284 +0x39
github.com/xtls/xray-core/transport/internet/splithttp.(*splitConn).Close(0xc000758fa0)
  github.com/xtls/xray-core/transport/internet/splithttp/connection.go:31 +0x5f
github.com/xtls/xray-core/proxy/trojan.(*Client).Process(0xc001220d20, {0x165cff8, 0xc000758ff0}, 0xc000059900, {0x165a340, 0xc000a49300})
  github.com/xtls/xray-core/proxy/trojan/client.go:164 +0xaf1
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000a49300, {0x165cfc0, 0xc000e1f0e0}, 0xc000059900)
  github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x388
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000a50a20, {0x165cfc0, 0xc000e1f0e0}, 0xc000059900, {{0x165ccb0, 0xc00121d080}, 0x1bb, 0x2})
  github.com/xtls/xray-core/app/dispatcher/default.go:481 +0xc26
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 2654
  github.com/xtls/xray-core/app/dispatcher/default.go:268 +0x56c
```
```golang
panic: close of closed channel

goroutine 359380 [running]:
github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...)
  github.com/quic-go/quic-go@v0.46.0/http3/body.go:124
github.com/quic-go/quic-go/http3.(*hijackableBody).Close(0xc00057b0b0)
  github.com/quic-go/quic-go@v0.46.0/http3/body.go:130 +0x2b
github.com/xtls/xray-core/transport/internet/splithttp.(*WaitReadCloser).Close(0x180a2b8?)
  github.com/xtls/xray-core/transport/internet/splithttp/client.go:284 +0x39
github.com/xtls/xray-core/transport/internet/splithttp.(*splitConn).Close(0xc000fb0dc0)
  github.com/xtls/xray-core/transport/internet/splithttp/connection.go:31 +0x5f
github.com/xtls/xray-core/proxy/trojan.(*Client).Process(0xc0000b6360, {0x165cff8, 0xc000fb0e10}, 0xc0000b6fc0, {0x165a340, 0xc00030f300})
  github.com/xtls/xray-core/proxy/trojan/client.go:164 +0xaf1
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc00030f300, {0x165cfc0, 0xc000707140}, 0xc0000b6fc0)
  github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x388
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000312900, {0x165cfc0, 0xc000707140}, 0xc0000b6fc0, {{0x165ccb0, 0xc000934d50}, 0x1bb, 0x2})
  github.com/xtls/xray-core/app/dispatcher/default.go:481 +0xc26
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 359379
  github.com/xtls/xray-core/app/dispatcher/default.go:268 +0x56c
```
在**运行**过程中，偶尔**崩溃**。目前共**崩溃** 2 次
https://t.me/projectXray/4099829?thread=4099814

**Comment by RPRX** [comment]
看了下代码，这纯粹就是 Trojan 出站调用了两次 Close() 而 quic-go H3 自己没处理好的问题，可能新版修了但 Xray 还没升

换 VLESS 还有这问题的话再开 issue

**Comment by RPRX** [comment]
或者你试试 stream-up，直连的话它和 stream-one 差不多

**Comment by RPRX** [comment]
在简化 stream-down 的代码时发现这个是 @mmmray 曾想解决的 quic-go http3 的 bug

**Comment by RPRX** [comment]
详见 https://github.com/quic-go/quic-go/issues/4637 ，遗憾的是修复该 bug 的 pr 未能成功合并：https://github.com/quic-go/quic-go/pull/4638

在考虑要不要修改 xtls/quic-go 的代码~~并等待有人用 google 账号去提交 pr~~

**Comment by RPRX** [comment]
XTLS/quic-go 合并了 https://github.com/quic-go/quic-go/pull/4638 ，然后 https://github.com/XTLS/Xray-core/commit/208f801986c38fc3307a4e955173acb9bea31e38 大幅简并代码，修好了一些 problems，按引入时间顺序：
1. stream-down resp.Body 最终没被 Close 的问题（此前 @mmmray 为解决这个 issue 的 lazyReader 不好调用 Close）
2. stream-one H3 会 panic 的问题（也就是这个 issue）
3. stream-one 无 remoteAddr、localAddr 的问题
4. stream-one XMUX LeftRequests 被减两次的问题

顺便看了下他们改的 browser dialer，给它加上 stream-up 支持应该挺简单的：
1. 只能 Chromium，且不能 stream-one，大概是收到响应头就不能再上传，类似于 HTTP/1.1，看来 Xray 服务端还得保持现状
2. `tlsSettings` 失效，XMUX 失效，不过可以上下行分离，可以加 gRPC header 伪装，再设个 HTTP 代理就能关掉 H3
5. 文档写的 `SNI == host == address` 不全对，其实可以改系统 host，或导进 Xray Freedom redirect 来指定 IP
6. XHTTP 刚禁了 mux.cool，若遇到浏览器连接数限制，可以多开几个浏览器或页面去加载 browser dialer

**Comment by xqzr** [comment]
> 换 VLESS 还有这问题的话再开 issue

v24.12.18
```golang
panic: close of closed channel

goroutine 109071 [running]:
github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...)
	github.com/quic-go/quic-go@v0.46.0/http3/body.go:124
github.com/quic-go/quic-go/http3.(*hijackableBody).Close(0xc000a0f110)
	github.com/quic-go/quic-go@v0.46.0/http3/body.go:130 +0x2b
github.com/xtls/xray-core/transport/internet/splithttp.(*WaitReadCloser).Close(0x1ac7d05?)
	github.com/xtls/xray-core/transport/internet/splithttp/client.go:296 +0x39
github.com/xtls/xray-core/transport/internet/splithttp.(*splitConn).Close(0xc000c86eb0)
	github.com/xtls/xray-core/transport/internet/splithttp/connection.go:31 +0x5f
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0xc0001b7680, {0x19124b0, 0xc00117a660}, 0xc0010ca760, {0x190f8a0, 0xc000ac7880})
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:293 +0x157c
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000ac7880, {0x19124b0, 0xc00117a660}, 0xc0010ca760)
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x388
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000ad46c0, {0x19124b0, 0xc00117a660}, 0xc0010ca760, {{0x1912210, 0xc0012c72f0}, 0x1bb, 0x2})
	github.com/xtls/xray-core/app/dispatcher/default.go:481 +0xc26
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 109070
	github.com/xtls/xray-core/app/dispatcher/default.go:268 +0x56c
```

**Comment by xqzr** [comment]
> v24.12.18

```golang
goroutine 7774 [running]:
github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...)
	github.com/quic-go/quic-go@v0.46.0/http3/body.go:124
github.com/quic-go/quic-go/http3.(*hijackableBody).Close(0xc000993e90)
	github.com/quic-go/quic-go@v0.46.0/http3/body.go:130 +0x2b
github.com/xtls/xray-core/transport/internet/splithttp.(*WaitReadCloser).Close(0x1ac7d05?)
	github.com/xtls/xray-core/transport/internet/splithttp/client.go:296 +0x39
github.com/xtls/xray-core/transport/internet/splithttp.(*splitConn).Close(0xc00061a000)
	github.com/xtls/xray-core/transport/internet/splithttp/connection.go:31 +0x5f
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0xc00015e8d0, {0x19124b0, 0xc000861a40}, 0xc001074f20, {0x190f8a0, 0xc000359880})
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:293 +0x157c
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000359880, {0x19124b0, 0xc000861a40}, 0xc001074f20)
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x388
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0003686c0, {0x19124b0, 0xc000861a40}, 0xc001074f20, {{0x1912210, 0xc000613140}, 0x1bb, 0x2})
	github.com/xtls/xray-core/app/dispatcher/default.go:481 +0xc26
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 7773
	github.com/xtls/xray-core/app/dispatcher/default.go:268 +0x56c
```

**Comment by RPRX** [comment]
@xqzr main 已经修了

**Comment by RPRX** [comment]
我想起来三年前给 flutter 提 pr 时有人替我这个号签了 Google CLA，所以刚刚给 quic-go 提了一个 pr：https://github.com/quic-go/quic-go/pull/4798

**Comment by RPRX** [comment]
https://github.com/quic-go/quic-go/pull/4798 已被合并，httptrace 也在 quic-go v0.49 的 milestone 里，v25 可以换回官方库了，~~虽然还要解决指纹问题~~
