### ISSUE TITLE
Kernel Crashed: panic: Calling Domain() on an IPv4Address.

### ISSUE THREAD

**Issue by Sinofine** [XTLS/Xray-core#473]
报错信息： https://pastebin.ubuntu.com/p/43yHpWctkM/
配置文件： https://pastebin.ubuntu.com/p/4vD83VKTmn/

**Comment by Sinofine** [comment]
pastebin的内容：
```
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
A unified platform for anti-censorship.
2021/04/03 21:48:45 [Info] infra/conf/serial: Reading config: /home/sinofine/.config/qv2ray/generated/config.gen.json
2021/04/03 21:48:45 [Debug] app/log: Logger started
2021/04/03 21:48:45 [Info] app/dns: DNS: created UDP client initialized for 127.0.0.1:53
2021/04/03 21:48:45 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
2021/04/03 21:48:45 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
2021/04/03 21:48:45 [Info] app/dns: DNS: created UDP client initialized for 8.8.4.4:53
2021/04/03 21:48:45 [Debug] app/stats: create new counter inbound>>>QV2RAY_API_INBOUND>>>traffic>>>uplink
2021/04/03 21:48:45 [Debug] app/stats: create new counter inbound>>>QV2RAY_API_INBOUND>>>traffic>>>downlink
panic: Calling Domain() on an IPv4Address.

goroutine 1 [running]:
github.com/xtls/xray-core/common/net.ipv4Address.Domain(...)
        github.com/xtls/xray-core/common/net/address.go:132
github.com/xtls/xray-core/transport/internet/tcp.ListenTCP(0x556aac99b070, 0xc00019e020, 0x556aac99c3e8, 0xc00057b8b0, 0xc000230000, 0xc0004f2140, 0xc000613870, 0x10, 0x10, 0x7f9358082108, ...)
        github.com/xtls/xray-core/transport/internet/tcp/hub.go:48 +0x103
github.com/xtls/xray-core/transport/internet.ListenTCP(0x556aac99b070, 0xc00019e020, 0x556aac99c3e8, 0xc00057b8b0, 0x0, 0xc0004f2140, 0xc000613870, 0x7ffc1b6a534e, 0x556aac999410, 0x9, ...)
        github.com/xtls/xray-core/transport/internet/tcp_hub.go:73 +0x29d
github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start(0xc0005c52c0, 0xc00033aea0, 0xc0003a1bd8)
        github.com/xtls/xray-core/app/proxyman/inbound/worker.go:120 +0xb7
github.com/xtls/xray-core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc0006b63c0, 0xc0005f84b0, 0xc0003a1c20)
        github.com/xtls/xray-core/app/proxyman/inbound/always.go:153 +0x68
github.com/xtls/xray-core/app/proxyman/inbound.(*Manager).Start(0xc000032580, 0x0, 0x0)
        github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:100 +0x103
github.com/xtls/xray-core/core.(*Instance).Start(0xc0005fc0a0, 0x0, 0x0)
        github.com/xtls/xray-core/core/xray.go:347 +0xad
main.executeRun(0x556aaceb22e0, 0xc0001a4030, 0x0, 0x0)
        github.com/xtls/xray-core/main/run.go:79 +0x12a
github.com/xtls/xray-core/main/commands/base.Execute()
        github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x285
main.main()
        github.com/xtls/xray-core/main/main.go:22 +0x16f
```

```
{
    "api": {
        "services": [
            "ReflectionService",
            "HandlerService",
            "LoggerService",
            "StatsService"
        ],
        "tag": "QV2RAY_API"
    },
    "dns": {
        "servers": [
            "127.0.0.1",
            "1.1.1.1",
            "8.8.8.8",
            "8.8.4.4"
        ]
    },
    "fakedns": {
        "ipPool": "240.0.0.0/8",
        "poolSize": 65535
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 15490,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "sniffing": {
            },
            "tag": "QV2RAY_API_INBOUND"
        },
        {
            "listen": "0.0.0.0",
            "port": 8889,
            "protocol": "http",
            "settings": {
                "allowTransparent": true,
                "timeout": 300
            },
            "sniffing": {
            },
            "tag": "http_IN"
        },
        {
            "listen": "0.0.0.0",
            "port": 1089,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true
            },
            "sniffing": {
            },
            "tag": "socks_IN"
        },
        {
            "listen": "127.0.0.1",
            "port": 0,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "",
                "followRedirect": true,
                "network": "tcp",
                "port": 0,
                "timeout": 0
            },
            "sniffing": {
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            },
            "tag": "tproxy_IN"
        },
        {
            "listen": "::1",
            "port": 0,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "",
                "followRedirect": true,
                "network": "tcp",
                "port": 0,
                "timeout": 0
            },
            "sniffing": {
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            },
            "tag": "tproxy_IN_V6"
        }
    ],
    "log": {
        "loglevel": "debug"
    },
    "outbounds": [
        {
            "_QV2RAY_USE_GLOBAL_FORWARD_PROXY_": false,
            "protocol": "shadowsocks",
            "sendThrough": "0.0.0.0",
            "settings": {
                "servers": [
                    {
                    }
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "sinoazure-outline6"
        },
        {
            "protocol": "freedom",
            "sendThrough": "0.0.0.0",
            "settings": {
                "domainStrategy": "AsIs",
                "redirect": ":0"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "DIRECT"
        },
        {
            "protocol": "blackhole",
            "sendThrough": "0.0.0.0",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "BLACKHOLE"
        }
    ],
    "policy": {
        "system": {
            "statsInboundDownlink": true,
            "statsInboundUplink": true,
            "statsOutboundDownlink": true,
            "statsOutboundUplink": true
        }
    },
    "routing": {
        "domainMatcher": "mph",
        "domainStrategy": "AsIs",
        "rules": [
            {
                "inboundTag": [
                    "QV2RAY_API_INBOUND"
                ],
                "outboundTag": "QV2RAY_API",
                "type": "field"
            },
            {
                "outboundTag": "DIRECT",
                "protocol": [
                    "bittorrent"
                ],
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "ip": [
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "nmcheck.gnome.org"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "DIRECT",
                "type": "field"
            }
        ]
    },
    "stats": {
    }
}
```

**Comment by rprx** [comment]
不能 listen port 0
