### ISSUE TITLE
运行不到一天就挂了，出现 panic: extending out of bound，挂掉之前在用gRPC

### ISSUE THREAD

**Issue by wc7086** [XTLS/Xray-core#596]
我是用UDS通信的，挂掉又自动重启之后gRPC就连不上了，必须删掉 grpc.sock 之后重启xray。掉线之前一直在用gRPC，且开启multi。

以及希望尽快修复xray-core生成的socket文件的权限问题。

## 服务器环境
用了萌咖的vvr0，但是另一个瓦工的参数只有这个服务器的四分之一，一模一样的环境没出现过此问题。
```
 CPU Model            : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
 CPU Cores            : 2 Cores 2500.004 MHz x86_64
 CPU Cache            : 33792 KB 
 OS                   : Debian GNU/Linux 10 (64 Bit) KVM
 Kernel               : 4.14.153
 Total Space          : 1.7 GB / 6.9 GB 
 Total RAM            : 368 MB / 961 MB (468 MB Buff)
 Total SWAP           : 6 MB / 974 MB
 Uptime               : 3 days 17 hour 35 min
 Load Average         : 0.07, 0.02, 0.00
 TCP CC               : bbr
 ASN & ISP            : AS16509, Amazon Technologies Inc.
 Organization         : AWS EC2 (ap-east-1)
 Location             : Hong Kong, Hong Kong / HK
 Region               : Central and Western
```
nginx version: nginx/1.21.0
Xray-core version: 1.4.2

## 日志及配置文件

<details>
<summary>xray服务端日志</summary>

```log
panic: extending out of bound

goroutine 730710 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
  github.com/xtls/xray-core/common/buf/buffer.go:98
github.com/xtls/xray-core/transport/internet/grpc/encoding.(*MultiHunkReaderWriter).ReadMultiBuffer(0xc000b8d200, 0x0, 0x0, 0xc0013d9701, 0x203000, 0x203000)
  github.com/xtls/xray-core/transport/internet/grpc/encoding/multiconn.go:90 +0x546
github.com/xtls/xray-core/common/buf.(*BufferedReader).Read(0xc0017f6e70, 0xc0005a6000, 0x2000, 0x2000, 0xf0f3e0, 0x7f2d14920228, 0xc0017f6fc0)
  github.com/xtls/xray-core/common/buf/reader.go:76 +0x9d
github.com/xtls/xray-core/common/net/cnc.(*connection).Read(0xc00057c460, 0xc0005a6000, 0x2000, 0x2000, 0xf0f3e0, 0x0, 0x7f2d14920228)
  github.com/xtls/xray-core/common/net/cnc/connection.go:96 +0x4c
github.com/xtls/xray-core/common/buf.(*Buffer).ReadFrom(0xc0017f6fc0, 0x7f2d14920228, 0xc00057c460, 0x7f2d14920228, 0xc00057c460, 0x0)
  github.com/xtls/xray-core/common/buf/buffer.go:214 +0x73
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process(0xc000033900, 0x10d45e0, 0xc0017f6f90, 0x4, 0x7f2d149201d0, 0xc00057c460, 0x10d4c38, 0xc00008dcc0, 0x0, 0x0)
  github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:192 +0x2a5
github.com/xtls/xray-core/app/proxyman/inbound.(*dsWorker).callback(0xc00056db00, 0x7f2d149201d0, 0xc00057c460)
  github.com/xtls/xray-core/app/proxyman/inbound/worker.go:467 +0x48c
created by github.com/xtls/xray-core/app/proxyman/inbound.(*dsWorker).Start.func1
  github.com/xtls/xray-core/app/proxyman/inbound/worker.go:486 +0x52
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.5 linux/amd64)
A unified platform for anti-censorship.
```
</details>

<details>
<summary>nginx错误日志</summary>

```log
[error] 32#32: *36292 connect() to unix:/dev/shm/xray_unixsocket/grpc.sock failed (111: Connection refused) while connecting to upstream, client: unix:, server: example.com, request: "POST /demogrpc/TunMulti HTTP/2.0", upstream: "grpc://unix:/dev/shm/xray_unixsocket/grpc.sock:", host: "example.com"
```
</details>

<details>
<summary>xray服务端配置</summary>

```json
{
    "log": {
        "loglevel": "none"
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/demows",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
                    "certificates": [
                        {
                            "certificateFile": "/certs/example.com/fullchain.cer",
                            "keyFile": "/certs/example.com/example.com.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "/dev/shm/xray_unixsocket/grpc.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "demogrpc"
                }
            }
        },
        {
            "listen": "@/dev/shm/xray/ws.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/demows"
                }
            }
        },
        {
            "port": 999,
            "protocol": "shadowsocks",
            "settings": {
                "clients": [
                    {
                        "method": "chacha20-ietf-poly1305",
                        "password": "example"
                    }
                ],
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}
```
</details>

<details>
<summary>nginx配置</summary>

```nginx
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
    server_name example.com;

    root /usr/share/nginx/html/example.com;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;

    location /demogrpc {
        client_max_body_size 0;
        client_body_timeout 999999999m;
        grpc_read_timeout 999999999m;
        grpc_pass grpc://unix:/dev/shm/xray_unixsocket/grpc.sock;
    }
}
```
</details>

**Comment by wc7086** [comment]
又遇到了，也是用着gRPC的时候突然连不上了才发现（因为权限问题导致每次重启我都需要去给sock文件设置0666权限）

<details>
<summary>xray服务端日志</summary>

```
2021/06/19 02:15:02 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
panic: extending out of bound

goroutine 940556 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
	github.com/xtls/xray-core/common/buf/buffer.go:98
github.com/xtls/xray-core/transport/internet/grpc/encoding.(*MultiHunkReaderWriter).ReadMultiBuffer(0xc001c6f600, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/xtls/xray-core/transport/internet/grpc/encoding/multiconn.go:90 +0x546
github.com/xtls/xray-core/common/buf.(*BufferedReader).ReadMultiBuffer(0xc0002a4600, 0xc00077daa0, 0xc000689d10, 0x0, 0x6cb039, 0x0)
	github.com/xtls/xray-core/common/buf/reader.go:96 +0xb9
github.com/xtls/xray-core/common/net/cnc.(*connection).ReadMultiBuffer(0xc0006f6dc0, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/xtls/xray-core/common/net/cnc/connection.go:101 +0x2e
github.com/xtls/xray-core/common/buf.(*BufferedReader).ReadMultiBuffer(0xc0002a4750, 0xc001ba4e00, 0x1, 0x2, 0x0, 0x0)
	github.com/xtls/xray-core/common/buf/reader.go:96 +0xb9
github.com/xtls/xray-core/common/buf.copyInternal(0x10bf880, 0xc0002a4750, 0x10c0f00, 0xc00009ac58, 0xc0002c86d8, 0xb91e01, 0xc0002c86c0)
	github.com/xtls/xray-core/common/buf/copy.go:81 +0x49
github.com/xtls/xray-core/common/buf.Copy(0x10bf880, 0xc0002a4750, 0x10c0f00, 0xc00009ac58, 0xc00080c738, 0x1, 0x1, 0xc000c75f90, 0x0)
	github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func4(0x0, 0x0)
	github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:516 +0x405
github.com/xtls/xray-core/common/task.OnSuccess.func1(0xc00048d260, 0x0)
	github.com/xtls/xray-core/common/task/task.go:12 +0x2f
github.com/xtls/xray-core/common/task.Run.func1(0xc00009acb0, 0xc000f52360, 0xc0002c8690)
	github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
	github.com/xtls/xray-core/common/task/task.go:27 +0x152
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.5 linux/amd64)
A unified platform for anti-censorship.
2021/06/22 19:41:37 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
```
</details>

**Comment by wc7086** [comment]
又遇到了，这次也是必须删掉sock文件后并手动重启xray

<details>
<summary>xray服务端日志</summary>

```
2021/06/19 02:15:02 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
panic: extending out of bound

goroutine 940556 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
	github.com/xtls/xray-core/common/buf/buffer.go:98
github.com/xtls/xray-core/transport/internet/grpc/encoding.(*MultiHunkReaderWriter).ReadMultiBuffer(0xc001c6f600, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/xtls/xray-core/transport/internet/grpc/encoding/multiconn.go:90 +0x546
github.com/xtls/xray-core/common/buf.(*BufferedReader).ReadMultiBuffer(0xc0002a4600, 0xc00077daa0, 0xc000689d10, 0x0, 0x6cb039, 0x0)
	github.com/xtls/xray-core/common/buf/reader.go:96 +0xb9
github.com/xtls/xray-core/common/net/cnc.(*connection).ReadMultiBuffer(0xc0006f6dc0, 0x0, 0x0, 0x1, 0x0, 0x0)
	github.com/xtls/xray-core/common/net/cnc/connection.go:101 +0x2e
github.com/xtls/xray-core/common/buf.(*BufferedReader).ReadMultiBuffer(0xc0002a4750, 0xc001ba4e00, 0x1, 0x2, 0x0, 0x0)
	github.com/xtls/xray-core/common/buf/reader.go:96 +0xb9
github.com/xtls/xray-core/common/buf.copyInternal(0x10bf880, 0xc0002a4750, 0x10c0f00, 0xc00009ac58, 0xc0002c86d8, 0xb91e01, 0xc0002c86c0)
	github.com/xtls/xray-core/common/buf/copy.go:81 +0x49
github.com/xtls/xray-core/common/buf.Copy(0x10bf880, 0xc0002a4750, 0x10c0f00, 0xc00009ac58, 0xc00080c738, 0x1, 0x1, 0xc000c75f90, 0x0)
	github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func4(0x0, 0x0)
	github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:516 +0x405
github.com/xtls/xray-core/common/task.OnSuccess.func1(0xc00048d260, 0x0)
	github.com/xtls/xray-core/common/task/task.go:12 +0x2f
github.com/xtls/xray-core/common/task.Run.func1(0xc00009acb0, 0xc000f52360, 0xc0002c8690)
	github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
	github.com/xtls/xray-core/common/task/task.go:27 +0x152
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.5 linux/amd64)
A unified platform for anti-censorship.
2021/06/22 19:41:37 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
```
</details>

**Comment by hmol233** [comment]
如果方便的话，请提供更多信息。

**Comment by wc7086** [comment]
> 如果方便的话，请提供更多信息。

没想到会再次遇到这个问题，所以没做收集信息的准备，下次我会第一时间收集我能力范围内能收集到的信息。

**Comment by hmol233** [comment]
https://github.com/XTLS/Xray-core/pull/599 should solve this issue.

**Comment by wc7086** [comment]
> #599 should solve this issue.

这个问题很玄学，完全一样的环境，没重装过系统，那两次之后就没有再复现，所以不好测试是否解决。

**Comment by WorldKeeptrying** [comment]
建议在 Docker 环境下运行进行测试。Docker 的日志是整个容器完整的日志，先排查Docker是否有报错。这样才能确定不是由于宿主机的某些软件冲突造成的错误。Docker 可以保证整个容器内只有Nginx & Xray-core 。

Docker & VMware 专破所有玄学。

**Comment by wc7086** [comment]
> 建议在 Docker 环境下运行进行测试。

我当时就是放在docker里的。

>Docker 的日志是整个容器完整的日志，先排查Docker是否有报错。这样才能确定不是由于宿主机的某些软件冲突造成的错误。

我不是专业运维，对docker并不熟悉，所以当时我没想到去查看整个容器的完整日志

>Docker 可以保证整个容器内只有Nginx & Xray-core 。

本着容器最小化的原则，那个容器我只放了xray。

**Comment by badO1a5A90** [comment]
https://github.com/XTLS/Xray-core/pull/599 已merge
新版本xray v1.4.3 已经包含此修改, 这个问题先close了.
请尝试使用新版本, 如果还有同样问题, 可以重开问题.

**Comment by y1rn** [comment]
最新代码报了这个错, 客户端使用test 版本的shadowrocket.
```
Feb 28 17:17:10 arm xray[1594086]: panic: extending out of bound
Feb 28 17:17:10 arm xray[1594086]: goroutine 199 [running]:
Feb 28 17:17:10 arm xray[1594086]: github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
Feb 28 17:17:10 arm xray[1594086]:         github.com/xtls/xray-core/common/buf/buffer.go:126
Feb 28 17:17:10 arm xray[1594086]: github.com/xtls/xray-core/proxy/vless/encoding.XtlsPadding(0x40004d6c60, 0x0, 0x40003b6f20, 0x1?, {0xfa5000, 0x40004d6a50})
Feb 28 17:17:10 arm xray[1594086]:         github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:559 +0x780
Feb 28 17:17:10 arm xray[1594086]: github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func5()
Feb 28 17:17:10 arm xray[1594086]:         github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:629 +0x7a0
Feb 28 17:17:10 arm xray[1594086]: github.com/xtls/xray-core/common/task.Run.func1(0x40003f71a0?)
Feb 28 17:17:10 arm xray[1594086]:         github.com/xtls/xray-core/common/task/task.go:28 +0x34
Feb 28 17:17:10 arm xray[1594086]: created by github.com/xtls/xray-core/common/task.Run
Feb 28 17:17:10 arm xray[1594086]:         github.com/xtls/xray-core/common/task/task.go:27 +0xcc
Feb 28 17:17:10 arm systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
