### ISSUE TITLE
使用vmess+ws作为入口，xtls-rprx-splice作为出口流控时报错

### ISSUE THREAD

**Issue by OPPO9008** [XTLS/Xray-core#797]
服务端运行环境
Linux kka-desktop 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

服务器配置
```
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 8000,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "不便透露",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "不便透露",
            "port": 443,
            "users": [
              {
                "id": "不便透露",
		"flow": "xtls-rprx-splice",//可能的关键之处
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "serverName": "不便透露"
        }
      },
      "tag": "proxy1"
    },
    {
      "protocol": "freedom"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
}
```
报错内容
```
Xray 1.5.0 (Xray, Penetrates Everything.) Custom (go1.17.2 linux/amd64)
A unified platform for anti-censorship.
2021/11/03 22:02:47 [Info] infra/conf/serial: Reading config: /home/kka/服务器/config.json
panic: XTLS Splice: not TCP inbound

goroutine 546 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0xc00001c710, {0xf8e3a0, 0xc0007a9920}, {0x0, 0x0}, {0xf87a00, 0xc00001c718}, 0xc00008fe20, {0xf73e80, 0xc0008008d0}, ...)
	github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:210 +0x5e5
github.com/xtls/xray-core/proxy/vless/encoding.ReadV({0xf73a80, 0xc00030a270}, {0xf75000, 0xc000286aa0}, {0xf73e80, 0xc0008008d0}, 0xc0000a3e80, {0xf87a00, 0xc00001c718}, {0x0, ...}, ...)
	github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:236 +0xa5
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:240 +0x445
github.com/xtls/xray-core/common/task.OnSuccess.func1()
	github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0xc000800660)
	github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
	github.com/xtls/xray-core/common/task/task.go:27 +0xe5
```

**Comment by misaka-2021** [comment]
You cannot use "xtls" in "vmess+ws"

**Comment by yuhan6665** [comment]
Splice 模式的的使用限制：

- Linux 环境
- 入站协议为 Dokodemo door、Socks、HTTP 等纯净的 TCP 连接, 或其它使用了 XTLS 的入站协议
- 出站协议为 VLESS + XTLS 或 Trojan + XTLS
