### ISSUE TITLE
Panic on android

### ISSUE THREAD

**Issue by cyber9723470** [XTLS/Xray-core#801]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5556d7fef8]

goroutine 282 [running]:
github.com/xtls/xray-core/app/router.(*LeastPingStrategy).PickOutbound(0x4001a711c0, {0x4001d98800, 0xb, 0x10})
        github.com/xtls/xray-core/app/router/strategy_leastping.go:26 +0x28
github.com/xtls/xray-core/app/router.(*Balancer).PickOutbound(0x4001a15040)
        github.com/xtls/xray-core/app/router/balancing.go:41 +0x168
github.com/xtls/xray-core/app/router.(*Rule).GetTag(...)
        github.com/xtls/xray-core/app/router/config.go:56
github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x4001152840, {0x55577da278, 0x40001a93e0})
        github.com/xtls/xray-core/app/router/router.go:76 +0x80
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0x4001154aa0, {0x55577c8220, 0x4001a0c1b0}, 0x400094aaa0, {{0x55577c9528, 0x40013bb590}, 0x2329, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:414 +0x2b0
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
        github.com/xtls/xray-core/app/dispatcher/default.go:234 +0x710

```

Configured with 
```
 "tag": "balancer_us",
                "strategy": {
                    "type": "leastPing"
                },
                "selector": [
                    "troj1",
                    "troj2",
                    "vmess1",
....
```

**Comment by cyber9723470** [comment]
@nekohasekai

**Comment by yuhan6665** [comment]
我看了一下应该修好了 你可以试试最新的 build
https://github.com/XTLS/Xray-core/actions/runs/1483843939
