### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by aztecrabbit** [XTLS/Xray-core#908]
Hi,

I'm importing 2 packages, from v2fly and xtls, and when I run the binary, an error occurred. Can I know how to avoid this?

```
panic: proto: file "common/serial/typed_message.proto" is already registered
	previously from: "github.com/v2fly/v2ray-core/v4/common/serial"
	currently from:  "github.com/xtls/xray-core/common/serial"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0xc7efe0, 0xc9f9d8}, {0xc7efe0, 0xc0001fef90})
	google.golang.org/protobuf@v1.27.1/reflect/protoregistry/registry.go:54 +0x1f4
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc00011e180, {0xc9f9d8, 0xc0001f16c0})
	google.golang.org/protobuf@v1.27.1/reflect/protoregistry/registry.go:128 +0x399
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0xa75622, 0x27}, {0x10d59a0, 0xd3, 0xd3}, 0x0, 0x1, 0x0, 0x0, {0xc89ea0, ...}, ...})
	google.golang.org/protobuf@v1.27.1/internal/filedesc/build.go:113 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0xa75622, 0x27}, {0x10d59a0, 0xd3, 0xd3}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...}, ...})
	google.golang.org/protobuf@v1.27.1/internal/filetype/build.go:139 +0x198
github.com/xtls/xray-core/common/serial.file_common_serial_typed_message_proto_init()
	github.com/xtls/xray-core@v1.5.2/common/serial/typed_message.pb.go:156 +0x198
github.com/xtls/xray-core/common/serial.init.0()
	github.com/xtls/xray-core@v1.5.2/common/serial/typed_message.pb.go:124 +0x17
```

**Comment by yuhan6665** [comment]
Usually core is for replacing each other. You can not build them together.
